learning_rate: 2.0e-5
num_epochs: 1
beta: 0.1
loss_type: dpo_norm
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
warmup_ratio: 0.03
max_seq_length: 2048
seed: 8
deepspeed_config: configs/deepspeed/zero2_no_offloading.json

lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
