"""Tests for `.claude/workflow.yaml` schema, loader, and lint round-trip.

Covers:

* Happy-path: the canonical YAML loads and resolves all internal references.
* Schema breakage: rename a column, expect raise.
* Schema breakage: omit `entry_status_label`, expect raise.
* Schema breakage: use the literal `any` sentinel, expect raise.
* Sagan routing views: dictionaries built from the YAML cover the dashboard
  columns and status mappings still in active use.
* Reference resolution: `(see workflow.yaml § <key>)` references in the
  fixture markdown resolve to a real key.
* Auto-generated tables in markers.md / SKILL.md re-render deterministically.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml
from pydantic import ValidationError

from explore_persona_space.workflow import WorkflowYaml, load_workflow_yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
WORKFLOW_PATH = REPO_ROOT / ".claude" / "workflow.yaml"


def test_schema_loads():
    """The committed workflow.yaml validates and round-trips with the
    full Phase-B-restored content depth."""
    workflow = load_workflow_yaml()
    assert workflow.version == 1
    assert "experiment" in workflow.issue_types
    # Sanity: at least the load-bearing statuses exist.
    names = {s.name for s in workflow.statuses}
    for required in ("proposed", "running", "awaiting_promotion", "blocked"):
        assert required in names, f"missing required status: {required}"
    # Phase B content-depth assertions: the restored yaml must carry the
    # full agent-facing reference data.
    assert len(workflow.columns) >= 5
    assert len(workflow.statuses) >= 12
    assert workflow.gates is not None
    assert len(workflow.halt_criteria) == 5
    assert len(workflow.markers) >= 25
    assert len(workflow.steps) >= 14


def test_label_to_column_round_trip():
    """The dict generated by the YAML covers every dashboard status mapping."""
    workflow = load_workflow_yaml()
    mapping = workflow.label_to_column()

    # Spot-check the load-bearing mappings used by Sagan migration helpers.
    assert mapping["status:proposed"] == "To do"
    assert mapping["status:running"] == "In flight"
    assert mapping["status:reviewing"] == "In flight"
    assert mapping["status:awaiting_promotion"] == "Awaiting promotion"
    assert mapping["status:done_experiment"] == "Done"
    assert mapping["status:done_impl"] == "Done"
    assert mapping["status:blocked"] == "Blocked"
    assert mapping["status:archived"] == "Archived"
    # Priority labels. Promotions route only to Useful / Not useful.
    assert mapping["clean-results:draft"] == "Awaiting promotion"
    assert mapping["clean-results:useful"] == "Useful"
    assert mapping["clean-results:not-useful"] == "Not useful"
    assert "clean-results" not in mapping


def test_priority_labels_first_match_order():
    """Priority labels are read in the order declared in workflow.yaml; the
    FIRST-MATCH-WINS contract requires `clean-results:draft` to come first
    (defensive — half-applied promotes stay observably unfinished in
    "Awaiting promotion" until reconciled)."""
    workflow = load_workflow_yaml()
    names = workflow.priority_label_names()
    assert names[0] == "clean-results:draft"
    assert "clean-results:useful" in names
    assert "clean-results:not-useful" in names
    # Bare `clean-results` was retired together with the "Clean results"
    # column; no row should re-introduce it as a priority label.
    assert "clean-results" not in names


def test_unknown_column_in_status_raises():
    """A status pointing at a bogus column fails validation."""
    raw = yaml.safe_load(WORKFLOW_PATH.read_text())
    raw["statuses"][0]["column"] = "Nonexistent"
    with pytest.raises(ValueError) as excinfo:
        WorkflowYaml.model_validate(raw)
    assert "unknown column" in str(excinfo.value)


def test_step_with_any_sentinel_raises():
    """The literal `any` is rejected in entry_status_label per the §1 schema
    (otherwise §5's status:blocked → full-replay rule fails to detect drift)."""
    raw = yaml.safe_load(WORKFLOW_PATH.read_text())
    raw["steps"][0]["entry_status_label"] = ["any"]
    with pytest.raises((ValueError, ValidationError)) as excinfo:
        WorkflowYaml.model_validate(raw)
    assert "any" in str(excinfo.value).lower()


def test_step_with_empty_entry_label_raises():
    """An empty entry_status_label list fails (the field is min_length=1)."""
    raw = yaml.safe_load(WORKFLOW_PATH.read_text())
    raw["steps"][0]["entry_status_label"] = []
    with pytest.raises(ValidationError):
        WorkflowYaml.model_validate(raw)


def test_step_unknown_status_raises():
    """A step whose entry_status_label references a non-existent status is
    rejected — would otherwise let §5 jump to a step that can never be
    legitimately entered."""
    raw = yaml.safe_load(WORKFLOW_PATH.read_text())
    raw["steps"][0]["entry_status_label"] = ["frobnicating"]
    with pytest.raises(ValueError) as excinfo:
        WorkflowYaml.model_validate(raw)
    assert "frobnicating" in str(excinfo.value)


def test_step_unknown_next_expected_step_raises():
    """next_expected_step pointing to a removed step id is rejected."""
    raw = yaml.safe_load(WORKFLOW_PATH.read_text())
    raw["steps"][-1]["next_expected_step"] = "step-that-was-renamed"
    with pytest.raises(ValueError) as excinfo:
        WorkflowYaml.model_validate(raw)
    assert "next_expected_step" in str(excinfo.value)


def test_marker_kind_unknown_for_posts_marker_raises():
    """A step whose posts_marker references an undeclared marker kind is
    rejected. Catches typos like 'experiment-implementions' for
    'experiment-implementation'."""
    raw = yaml.safe_load(WORKFLOW_PATH.read_text())
    # Find a step that already has a posts_marker.
    target = next(s for s in raw["steps"] if s.get("posts_marker"))
    target["posts_marker"] = "no-such-marker"
    with pytest.raises(ValueError) as excinfo:
        WorkflowYaml.model_validate(raw)
    assert "no-such-marker" in str(excinfo.value)


def test_duplicate_status_name_raises():
    """Two statuses with the same name fail validation."""
    raw = yaml.safe_load(WORKFLOW_PATH.read_text())
    raw["statuses"].append(dict(raw["statuses"][0]))
    with pytest.raises(ValueError) as excinfo:
        WorkflowYaml.model_validate(raw)
    assert "duplicate" in str(excinfo.value).lower()


def test_terminal_sentinel_accepted():
    """next_expected_step: terminal is the only non-step sentinel allowed —
    it must validate without error."""
    raw = yaml.safe_load(WORKFLOW_PATH.read_text())
    # Confirm at least one step today uses the terminal sentinel; if none do,
    # add one for the test, ensure it validates.
    has_terminal = any(s["next_expected_step"] == "terminal" for s in raw["steps"])
    assert has_terminal, "expected at least one step to point at terminal"
    WorkflowYaml.model_validate(raw)  # should not raise


def test_load_workflow_yaml_caches(tmp_path):
    """Repeated calls return the same instance (cheap)."""
    a = load_workflow_yaml()
    b = load_workflow_yaml()
    assert a is b


def test_render_active_vs_awaiting_table_includes_user_gates():
    """The auto-generated 'Active vs awaiting-user' table flags every
    user-gated state. Catches a YAML edit that silently flipped
    `user_gated: true` → `false`."""
    from scripts.workflow_lint import render_active_vs_awaiting_table

    workflow = load_workflow_yaml()
    table = render_active_vs_awaiting_table(workflow)
    # Statuses we know are user-gated MUST appear in bold-yes.
    assert "| `plan_pending` |" in table
    # User-gated states use the bold marker.
    plan_pending_row = next(
        line for line in table.splitlines() if line.startswith("| `plan_pending`")
    )
    assert "**yes**" in plan_pending_row
    # Active-state rows use the plain "no" marker.
    running_row = next(line for line in table.splitlines() if line.startswith("| `running`"))
    assert "no |" in running_row


def test_render_marker_kinds_table_covers_all_kinds():
    """Every marker kind in the YAML has a row in the rendered table."""
    from scripts.workflow_lint import render_marker_kinds_table

    workflow = load_workflow_yaml()
    table = render_marker_kinds_table(workflow)
    for marker in workflow.markers:
        assert f"| `{marker.kind}` |" in table, f"missing row: {marker.kind}"


def test_steps_no_unreachable_terminal_orphans():
    """Every step (except terminals) must have a next_expected_step that
    resolves either to another step or the literal 'terminal'. Catches the
    forgotten-rewire case after a step rename."""
    workflow = load_workflow_yaml()
    ids = {s.id for s in workflow.steps} | {"terminal"}
    for step in workflow.steps:
        assert step.next_expected_step in ids


def test_reviewer_pairs_preserved():
    """The reviewer_pairs block (added post-GH-migration; the GH-era yaml
    lacked it) MUST survive Phase B's restoration. Each pair must have a
    `reviewers` list and a `markers` list. The three load-bearing pair
    keys must all be present."""
    raw = yaml.safe_load(WORKFLOW_PATH.read_text())
    assert "reviewer_pairs" in raw, "Phase B regression: reviewer_pairs block dropped"
    pairs = raw["reviewer_pairs"]["pairs"]
    for required_pair in ("code_review", "interpretation", "clean_result"):
        assert required_pair in pairs, f"missing reviewer_pair: {required_pair}"
        pair = pairs[required_pair]
        assert "reviewers" in pair and len(pair["reviewers"]) == 2
        assert "markers" in pair and len(pair["markers"]) == 2


def test_reviewer_pair_markers_are_known_kinds():
    """Every marker listed under reviewer_pairs.pairs.*.markers MUST exist
    in workflow.markers. Catches typos and orphaned references."""
    workflow = load_workflow_yaml()
    raw = yaml.safe_load(WORKFLOW_PATH.read_text())
    known_kinds = {m.kind for m in workflow.markers}
    for pair_name, pair in raw["reviewer_pairs"]["pairs"].items():
        for marker_ref in pair["markers"]:
            assert marker_ref in known_kinds, (
                f"reviewer_pairs.pairs.{pair_name}.markers references "
                f"unknown marker kind {marker_ref!r}"
            )


def test_step_entry_status_labels_resolve():
    """Every step's entry_status_label list MUST reference real status
    names declared in workflow.statuses. The Pydantic validator already
    enforces this, but this test makes the invariant a first-class
    assertion (catches an edit that adds a new step pointing at a
    not-yet-declared status)."""
    workflow = load_workflow_yaml()
    valid = {s.name for s in workflow.statuses}
    for step in workflow.steps:
        for label in step.entry_status_label:
            assert label in valid, (
                f"step {step.id!r}: entry_status_label {label!r} not in "
                f"declared statuses (valid={sorted(valid)})"
            )


def test_markers_have_fields():
    """Every marker MUST carry a non-empty `fields` description. The GH-era
    contract: downstream agents read `fields` to know what payload shape to
    write. An empty `fields` string means a marker was added to the names
    list without its schema being documented."""
    workflow = load_workflow_yaml()
    for marker in workflow.markers:
        assert marker.fields.strip(), (
            f"marker {marker.kind!r} has empty `fields`; document the expected payload shape"
        )


def test_gates_full_shape():
    """Phase B gates restoration: inline + park_and_wait + conditional all
    present with the expected counts."""
    workflow = load_workflow_yaml()
    assert workflow.gates is not None
    # 7 inline gates: the 5 from the GH-era contract + experiment_goal
    # (which replaced why_experiment on 2026-05-24) + smoke_architecture
    # (added by Fix #1 of the #397 post-mortem batch, 2026-05-27).
    assert len(workflow.gates.inline) == 7
    inline_names = {g.name for g in workflow.gates.inline}
    assert "experiment_goal" in inline_names
    assert "smoke_architecture" in inline_names
    # 1 park-and-wait gate (awaiting_promotion).
    assert len(workflow.gates.park_and_wait) == 1
    assert workflow.gates.park_and_wait[0].name == "awaiting_promotion"
    # 5 conditional gates: TDD + experiment_goal_refine (clarifier/planner
    # Goal-sharpening, added 2026-05-24 alongside the Goal contract) +
    # whack_a_mole_pivot (Fix #6) + compute_deviation_resolution (Fix #4),
    # both added by the #397 post-mortem batch on 2026-05-27, +
    # living_docs_update (living-docs integration, 2026-05-28).
    conditional_names = {g.name for g in workflow.gates.conditional}
    assert conditional_names == {
        "tdd_gate",
        "experiment_goal_refine",
        "whack_a_mole_pivot",
        "compute_deviation_resolution",
        "living_docs_update",
    }


def test_halt_criteria_count_and_names():
    """halt_criteria pinned to the names the 2026-05-22 revision installed
    (block-only-when-user-input-genuinely-needed philosophy). The retired
    `subagent_blocker` and `infra_respawn_cap` entries moved to
    pivot_criteria; what remains is the 5 conditions that legitimately
    require user input."""
    workflow = load_workflow_yaml()
    assert len(workflow.halt_criteria) == 5
    expected_names = {
        "outside_worktree_writes",
        "api_contract_change",
        "subagent_blocker_with_needs_user",
        "factual_question_only_user_knows",
        "completion_audit_incomplete",
    }
    actual = {h.name for h in workflow.halt_criteria}
    assert actual == expected_names, f"halt_criteria names drift: {actual ^ expected_names}"


def test_ensemble_review_doubled_steps_resolve():
    """ensemble_review.doubled_steps entries with reconcile_mode='marker'
    MUST have a reconcile_marker that exists in workflow.markers. The
    schema validates this — the test pins the contract."""
    workflow = load_workflow_yaml()
    assert workflow.ensemble_review is not None
    known_kinds = {m.kind for m in workflow.markers}
    marker_mode_count = 0
    for entry in workflow.ensemble_review.doubled_steps:
        if entry.reconcile_mode == "marker":
            marker_mode_count += 1
            assert entry.reconcile_marker in known_kinds
    # At least one entry uses marker-mode reconciliation.
    assert marker_mode_count >= 1


def test_subagent_halt_conditions_present():
    """Phase B restoration: subagent_halt_conditions populated."""
    workflow = load_workflow_yaml()
    assert len(workflow.subagent_halt_conditions) >= 5
    subagents = {row.subagent for row in workflow.subagent_halt_conditions}
    # Spot-check that the load-bearing subagents are covered.
    for required in (
        "consistency-checker",
        "interpretation-critic",
        "clean-result-critic",
        "upload-verifier",
    ):
        assert required in subagents, f"missing subagent halt row: {required}"


def test_reconciler_md_uses_only_canonical_reconcile_marker():
    """reconciler.md must reference ONLY the canonical marker-mode reconcile
    kind ``epm:review-reconcile`` (role carried in the body's
    ``**Role under adjudication:**`` field) plus the in-context
    ``epm:plan-critique-reconcile`` stdout tag. Catches the role-specific
    marker drift fixed 2026-05-28: reconciler.md had instructed the reconciler
    to post ``epm:code-review-reconcile`` / ``epm:interp-critique-reconcile``
    etc., which are invisible to the ``/issue`` state machine + workflow.yaml
    registry that key only off ``epm:review-reconcile`` (live history showed
    12 orphaned ``code-review-reconcile`` markers as a result)."""
    import re

    reconciler = (REPO_ROOT / ".claude" / "agents" / "reconciler.md").read_text()
    workflow = load_workflow_yaml()
    known_kinds = {m.kind for m in workflow.markers}

    allowed = {"epm:review-reconcile", "epm:plan-critique-reconcile"}
    found = set(re.findall(r"epm:[a-z-]*reconcile", reconciler))
    forbidden = found - allowed
    assert not forbidden, (
        f"reconciler.md names non-canonical reconcile marker kind(s) {sorted(forbidden)}; "
        f"marker mode must use `epm:review-reconcile` (role in body field), "
        f"in-context mode `epm:plan-critique-reconcile`"
    )
    # The canonical marker-mode kind MUST be a registered events.jsonl marker.
    assert "epm:review-reconcile" in known_kinds, (
        "epm:review-reconcile missing from workflow.yaml markers registry"
    )
    # The in-context tag is printed to stdout only and intentionally is NOT a
    # registered events.jsonl marker.
    assert "epm:plan-critique-reconcile" not in known_kinds, (
        "epm:plan-critique-reconcile is an in-context stdout tag; it must NOT "
        "be registered as an events.jsonl marker kind"
    )


def test_reviewer_pairs_reconciler_marker_is_canonical():
    """The reviewer_pairs.reconciler.marker AND every marker-mode
    doubled_steps[*].reconcile_marker resolve to the single canonical
    ``epm:review-reconcile`` kind — there is exactly ONE marker-mode reconcile
    kind, with the adjudicated role distinguished by the marker body field."""
    raw = yaml.safe_load(WORKFLOW_PATH.read_text())
    assert raw["reviewer_pairs"]["reconciler"]["marker"] == "epm:review-reconcile"
    workflow = load_workflow_yaml()
    marker_mode_markers = {
        e.reconcile_marker
        for e in workflow.ensemble_review.doubled_steps
        if e.reconcile_mode == "marker"
    }
    assert marker_mode_markers == {"epm:review-reconcile"}, (
        f"marker-mode reconcile kinds drifted: {sorted(marker_mode_markers)}"
    )
