"""Tests for `.claude/workflow.yaml` schema, loader, and lint round-trip.

Covers:

* Happy-path: the canonical YAML loads and resolves all internal references.
* Schema breakage: rename a column, expect raise.
* Schema breakage: omit `entry_status_label`, expect raise.
* Schema breakage: use the literal `any` sentinel, expect raise.
* Sagan routing views: dictionaries built from the YAML cover the dashboard
  columns and status mappings still in active use.
* Reference resolution: `(see workflow.yaml § <key>)` references in the
  fixture markdown resolve to a real key.
* Auto-generated tables in markers.md / SKILL.md re-render deterministically.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml
from pydantic import ValidationError

from explore_persona_space.workflow import WorkflowYaml, load_workflow_yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
WORKFLOW_PATH = REPO_ROOT / ".claude" / "workflow.yaml"


def test_schema_loads():
    """The committed workflow.yaml validates and round-trips."""
    workflow = load_workflow_yaml()
    assert workflow.version == 1
    assert "experiment" in workflow.issue_types
    # Sanity: at least the load-bearing statuses exist.
    names = {s.name for s in workflow.statuses}
    for required in ("proposed", "running", "awaiting_promotion", "blocked"):
        assert required in names, f"missing required status: {required}"


def test_label_to_column_round_trip():
    """The dict generated by the YAML covers every dashboard status mapping."""
    workflow = load_workflow_yaml()
    mapping = workflow.label_to_column()

    # Spot-check the load-bearing mappings used by Sagan migration helpers.
    assert mapping["status:proposed"] == "To do"
    assert mapping["status:running"] == "In flight"
    assert mapping["status:reviewing"] == "In flight"
    assert mapping["status:awaiting_promotion"] == "Awaiting promotion"
    assert mapping["status:done_experiment"] == "Done"
    assert mapping["status:done_impl"] == "Done"
    assert mapping["status:blocked"] == "Blocked"
    assert mapping["status:archived"] == "Archived"
    # Priority labels. Promotions route only to Useful / Not useful.
    assert mapping["clean-results:draft"] == "Awaiting promotion"
    assert mapping["clean-results:useful"] == "Useful"
    assert mapping["clean-results:not-useful"] == "Not useful"
    assert "clean-results" not in mapping


def test_priority_labels_first_match_order():
    """Priority labels are read in the order declared in workflow.yaml; the
    FIRST-MATCH-WINS contract requires `clean-results:draft` to come first
    (defensive — half-applied promotes stay observably unfinished in
    "Awaiting promotion" until reconciled)."""
    workflow = load_workflow_yaml()
    names = workflow.priority_label_names()
    assert names[0] == "clean-results:draft"
    assert "clean-results:useful" in names
    assert "clean-results:not-useful" in names
    # Bare `clean-results` was retired together with the "Clean results"
    # column; no row should re-introduce it as a priority label.
    assert "clean-results" not in names


def test_unknown_column_in_status_raises():
    """A status pointing at a bogus column fails validation."""
    raw = yaml.safe_load(WORKFLOW_PATH.read_text())
    raw["statuses"][0]["column"] = "Nonexistent"
    with pytest.raises(ValueError) as excinfo:
        WorkflowYaml.model_validate(raw)
    assert "unknown column" in str(excinfo.value)


def test_step_with_any_sentinel_raises():
    """The literal `any` is rejected in entry_status_label per the §1 schema
    (otherwise §5's status:blocked → full-replay rule fails to detect drift)."""
    raw = yaml.safe_load(WORKFLOW_PATH.read_text())
    raw["steps"][0]["entry_status_label"] = ["any"]
    with pytest.raises((ValueError, ValidationError)) as excinfo:
        WorkflowYaml.model_validate(raw)
    assert "any" in str(excinfo.value).lower()


def test_step_with_empty_entry_label_raises():
    """An empty entry_status_label list fails (the field is min_length=1)."""
    raw = yaml.safe_load(WORKFLOW_PATH.read_text())
    raw["steps"][0]["entry_status_label"] = []
    with pytest.raises(ValidationError):
        WorkflowYaml.model_validate(raw)


def test_step_unknown_status_raises():
    """A step whose entry_status_label references a non-existent status is
    rejected — would otherwise let §5 jump to a step that can never be
    legitimately entered."""
    raw = yaml.safe_load(WORKFLOW_PATH.read_text())
    raw["steps"][0]["entry_status_label"] = ["frobnicating"]
    with pytest.raises(ValueError) as excinfo:
        WorkflowYaml.model_validate(raw)
    assert "frobnicating" in str(excinfo.value)


def test_step_unknown_next_expected_step_raises():
    """next_expected_step pointing to a removed step id is rejected."""
    raw = yaml.safe_load(WORKFLOW_PATH.read_text())
    raw["steps"][-1]["next_expected_step"] = "step-that-was-renamed"
    with pytest.raises(ValueError) as excinfo:
        WorkflowYaml.model_validate(raw)
    assert "next_expected_step" in str(excinfo.value)


def test_marker_kind_unknown_for_posts_marker_raises():
    """A step whose posts_marker references an undeclared marker kind is
    rejected. Catches typos like 'experiment-implementions' for
    'experiment-implementation'."""
    raw = yaml.safe_load(WORKFLOW_PATH.read_text())
    # Find a step that already has a posts_marker.
    target = next(s for s in raw["steps"] if s.get("posts_marker"))
    target["posts_marker"] = "no-such-marker"
    with pytest.raises(ValueError) as excinfo:
        WorkflowYaml.model_validate(raw)
    assert "no-such-marker" in str(excinfo.value)


def test_duplicate_status_name_raises():
    """Two statuses with the same name fail validation."""
    raw = yaml.safe_load(WORKFLOW_PATH.read_text())
    raw["statuses"].append(dict(raw["statuses"][0]))
    with pytest.raises(ValueError) as excinfo:
        WorkflowYaml.model_validate(raw)
    assert "duplicate" in str(excinfo.value).lower()


def test_terminal_sentinel_accepted():
    """next_expected_step: terminal is the only non-step sentinel allowed —
    it must validate without error."""
    raw = yaml.safe_load(WORKFLOW_PATH.read_text())
    # Confirm at least one step today uses the terminal sentinel; if none do,
    # add one for the test, ensure it validates.
    has_terminal = any(s["next_expected_step"] == "terminal" for s in raw["steps"])
    assert has_terminal, "expected at least one step to point at terminal"
    WorkflowYaml.model_validate(raw)  # should not raise


def test_load_workflow_yaml_caches(tmp_path):
    """Repeated calls return the same instance (cheap)."""
    a = load_workflow_yaml()
    b = load_workflow_yaml()
    assert a is b


def test_render_active_vs_awaiting_table_includes_user_gates():
    """The auto-generated 'Active vs awaiting-user' table flags every
    user-gated state. Catches a YAML edit that silently flipped
    `user_gated: true` → `false`."""
    from scripts.workflow_lint import render_active_vs_awaiting_table

    workflow = load_workflow_yaml()
    table = render_active_vs_awaiting_table(workflow)
    # Statuses we know are user-gated MUST appear in bold-yes.
    assert "| `plan_pending` |" in table
    # User-gated states use the bold marker.
    plan_pending_row = next(
        line for line in table.splitlines() if line.startswith("| `plan_pending`")
    )
    assert "**yes**" in plan_pending_row
    # Active-state rows use the plain "no" marker.
    running_row = next(line for line in table.splitlines() if line.startswith("| `running`"))
    assert "no |" in running_row


def test_render_marker_kinds_table_covers_all_kinds():
    """Every marker kind in the YAML has a row in the rendered table."""
    from scripts.workflow_lint import render_marker_kinds_table

    workflow = load_workflow_yaml()
    table = render_marker_kinds_table(workflow)
    for marker in workflow.markers:
        assert f"| `{marker.kind}` |" in table, f"missing row: {marker.kind}"


def test_steps_no_unreachable_terminal_orphans():
    """Every step (except terminals) must have a next_expected_step that
    resolves either to another step or the literal 'terminal'. Catches the
    forgotten-rewire case after a step rename."""
    workflow = load_workflow_yaml()
    ids = {s.id for s in workflow.steps} | {"terminal"}
    for step in workflow.steps:
        assert step.next_expected_step in ids
