"""Compute-backend abstraction for `/issue` experiment runs.

The `/issue` skill dispatches each task to a :class:`~base.ComputeBackend`:

* :class:`runpod.RunPodBackend` (default) — wraps the existing
  ``scripts/pod_lifecycle.py`` flow with zero behavior change. A task with
  no ``backend:`` frontmatter routes here.
* SLURM cluster backend — opt-in via ``backend: cluster`` / ``backend: nibi``
  frontmatter. The selector's submit-and-park + fall-back-on-NotImplemented
  control flow is wired in :mod:`.selector`; the actual SLURM implementation
  (`slurm.py`, `slurm_monitor.py`) lands in slice 2.

The :class:`~base.PollResult` dataclass shape is intentionally the same
JSON shape that ``scripts/poll_pipeline.py`` produces, so the orchestrator's
existing JSON-line parsing keeps working unchanged.

See ``.claude/plans/2026-06-08_001932-slurm-cluster-backend-for-issue.md``
for the full plan; this slice (slice 1 of P1) ships the foundation only.
"""

from explore_persona_space.backends.artifacts import (
    EXPECTED_ARTIFACTS_HANDLE_KEY,
    ArtifactVerdict,
    ExpectedArtifacts,
    VerifierIO,
    confirm_artifacts_from_handle,
    verify_artifacts,
    write_completion_sentinel,
)
from explore_persona_space.backends.base import (
    BackendKind,
    BackendProbeError,
    ComputeBackend,
    PollResult,
    RunHandle,
    RunSpec,
)
from explore_persona_space.backends.gcp import (
    DEFAULT_GCLOUD_CONFIG,
    DEFAULT_IMAGE_FAMILY,
    DEFAULT_PRIMARY_ZONE,
    DEFAULT_PROJECT,
    INTENT_A100_40_FALLBACK,
    INTENT_TO_MACHINE,
    GcpBackend,
    GcpBackendError,
    GcpConfig,
    GcpProbeError,
    GcpProvisioningError,
    GcpWorkloadError,
    MachineSpec,
    a100_40_fallback_for_intent,
    audit_stale_gcp_vms,
    default_gcp_config,
    render_create_argv,
    render_startup_script,
)
from explore_persona_space.backends.issue_dispatch import (
    DispatchOutcome,
    TerminalTranslation,
    build_run_spec,
    classify_terminal_exception,
    default_handle_sidecar_path,
    deserialize_handle,
    dispatch_for_issue,
    normalize_backend_value,
    read_handle_sidecar,
    resolve_handle_sidecar_path,
    serialize_handle,
    write_handle_sidecar,
)
from explore_persona_space.backends.router import (
    CANCEL_LIVE_GRACE_SECONDS,
    DEFAULT_AUTO_LANE_ORDER,
    DEFAULT_FREE_LANE_ORDER,
    DEFAULT_POLL_INTERVAL,
    ENV_AUTO_LANE_ORDER,
    FREE_WAIT_SECONDS,
    LEASE_STORE_DIRNAME,
    MAX_GCP_ATTEMPTS_PER_DAY,
    ROUTE_REASON_AUTO_FALLBACK_GCP,
    ROUTE_REASON_AUTO_STARTED,
    ROUTE_REASON_NO_COMPUTE,
    ROUTE_REASON_OVERRIDE,
    ROUTE_REASON_RECONNECT,
    ROUTE_REASON_RUNPOD_FALLBACK,
    ROUTE_REASON_RUNPOD_FIRST,
    ROUTE_REASON_WORKLOAD_FAILURE,
    BackendPrepareError,
    GcpAttemptCapExceededError,
    Lease,
    LeaseStore,
    ManualAttentionRequiredError,
    NoComputeAvailableError,
    RouteAttempt,
    RouteError,
    RouterConfig,
    RouteResult,
    WorkloadSurfacedError,
    auto_lane_order,
    cancel_and_wait,
    canonicalize_spec,
    default_is_live,
    default_is_started,
    park_until_running_or_cap,
    rank_lanes,
    route,
    spec_hash,
)
from explore_persona_space.backends.runpod import RunPodBackend
from explore_persona_space.backends.selector import (
    SLURM_NOT_IMPLEMENTED_MESSAGE,
    BackendDecision,
    BackendSelectionError,
    select_backend,
)
from explore_persona_space.backends.slurm import (
    CLUSTER_CONFIGS,
    ClusterConfig,
    SbatchPlan,
    SlurmBackend,
    Stage,
    estimate_start_seconds,
    get_cluster_config,
    render_sbatch,
    ssh_estimate_start,
    stages_for_spec,
)

__all__ = [
    "CANCEL_LIVE_GRACE_SECONDS",
    "CLUSTER_CONFIGS",
    "DEFAULT_AUTO_LANE_ORDER",
    "DEFAULT_FREE_LANE_ORDER",
    "DEFAULT_GCLOUD_CONFIG",
    "DEFAULT_IMAGE_FAMILY",
    "DEFAULT_POLL_INTERVAL",
    "DEFAULT_PRIMARY_ZONE",
    "DEFAULT_PROJECT",
    "ENV_AUTO_LANE_ORDER",
    "EXPECTED_ARTIFACTS_HANDLE_KEY",
    "FREE_WAIT_SECONDS",
    "INTENT_A100_40_FALLBACK",
    "INTENT_TO_MACHINE",
    "LEASE_STORE_DIRNAME",
    "MAX_GCP_ATTEMPTS_PER_DAY",
    "ROUTE_REASON_AUTO_FALLBACK_GCP",
    "ROUTE_REASON_AUTO_STARTED",
    "ROUTE_REASON_NO_COMPUTE",
    "ROUTE_REASON_OVERRIDE",
    "ROUTE_REASON_RECONNECT",
    "ROUTE_REASON_RUNPOD_FALLBACK",
    "ROUTE_REASON_RUNPOD_FIRST",
    "ROUTE_REASON_WORKLOAD_FAILURE",
    "SLURM_NOT_IMPLEMENTED_MESSAGE",
    "ArtifactVerdict",
    "BackendDecision",
    "BackendKind",
    "BackendPrepareError",
    "BackendProbeError",
    "BackendSelectionError",
    "ClusterConfig",
    "ComputeBackend",
    "DispatchOutcome",
    "ExpectedArtifacts",
    "GcpAttemptCapExceededError",
    "GcpBackend",
    "GcpBackendError",
    "GcpConfig",
    "GcpProbeError",
    "GcpProvisioningError",
    "GcpWorkloadError",
    "Lease",
    "LeaseStore",
    "MachineSpec",
    "ManualAttentionRequiredError",
    "NoComputeAvailableError",
    "PollResult",
    "RouteAttempt",
    "RouteError",
    "RouteResult",
    "RouterConfig",
    "RunHandle",
    "RunPodBackend",
    "RunSpec",
    "SbatchPlan",
    "SlurmBackend",
    "Stage",
    "TerminalTranslation",
    "VerifierIO",
    "WorkloadSurfacedError",
    "a100_40_fallback_for_intent",
    "audit_stale_gcp_vms",
    "auto_lane_order",
    "build_run_spec",
    "cancel_and_wait",
    "canonicalize_spec",
    "classify_terminal_exception",
    "confirm_artifacts_from_handle",
    "default_gcp_config",
    "default_handle_sidecar_path",
    "default_is_live",
    "default_is_started",
    "deserialize_handle",
    "dispatch_for_issue",
    "estimate_start_seconds",
    "get_cluster_config",
    "normalize_backend_value",
    "park_until_running_or_cap",
    "rank_lanes",
    "read_handle_sidecar",
    "render_create_argv",
    "render_sbatch",
    "render_startup_script",
    "resolve_handle_sidecar_path",
    "route",
    "select_backend",
    "serialize_handle",
    "spec_hash",
    "ssh_estimate_start",
    "stages_for_spec",
    "verify_artifacts",
    "write_completion_sentinel",
    "write_handle_sidecar",
]
