#!/usr/bin/env python3
"""audit_stranded_task_commits.py — list tasks/ commits stranded on worktree branches.

For each active git worktree (under `.claude/worktrees/`) on its own branch,
list commits that exist on that branch but NOT on `main` and that touch
`tasks/`. Emit a markdown report under `logs/stranded_task_commits/`.

This is part of the worktree-staleness fix: before merging that fix, we need
to know which `tasks/` writes never made it to main because `task_workflow`
was committing to the wrong branch.

Report-only — does NOT cherry-pick. Human reads the report and decides per row.
"""

from __future__ import annotations

import datetime as dt
import json
import subprocess
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE.parent / "src"))

from explore_persona_space.task_workflow import registry_path  # noqa: E402

REPO = _HERE.parent
LOG_DIR = REPO / "logs" / "stranded_task_commits"


def _run(args: list[str], *, cwd: Path | None = None) -> str:
    return subprocess.run(
        args,
        cwd=cwd or REPO,
        check=True,
        capture_output=True,
        text=True,
    ).stdout


def list_worktrees() -> list[dict[str, str]]:
    """Parse `git worktree list --porcelain` into structured rows."""
    out = _run(["git", "worktree", "list", "--porcelain"])
    rows: list[dict[str, str]] = []
    cur: dict[str, str] = {}
    for line in out.splitlines():
        if not line:
            if cur:
                rows.append(cur)
                cur = {}
            continue
        if " " in line:
            key, val = line.split(" ", 1)
        else:
            key, val = line, ""
        cur[key] = val
    if cur:
        rows.append(cur)
    return rows


def stranded_commits(branch: str) -> list[dict[str, str]]:
    """Return commits on `branch` that aren't on `main` and touch `tasks/`."""
    try:
        out = _run(
            [
                "git",
                "log",
                f"main..{branch}",
                "--format=%H%x09%aI%x09%s",
                "--",
                "tasks/",
            ]
        )
    except subprocess.CalledProcessError as e:
        return [{"error": e.stderr.strip()}]
    rows = []
    for line in out.splitlines():
        parts = line.split("\t", 2)
        if len(parts) != 3:
            continue
        sha, date, subject = parts
        try:
            files = _run(
                [
                    "git",
                    "diff-tree",
                    "--no-commit-id",
                    "--name-only",
                    "-r",
                    sha,
                    "--",
                    "tasks/",
                ]
            ).splitlines()
        except subprocess.CalledProcessError:
            files = []
        rows.append({"sha": sha, "date": date, "subject": subject, "files": files})
    return rows


def task_ids_from_files(files: list[str]) -> set[int]:
    """Extract task IDs from `tasks/<status>/<N>/...` paths."""
    ids: set[int] = set()
    for f in files:
        parts = f.split("/")
        if len(parts) >= 3 and parts[0] == "tasks":
            try:
                ids.add(int(parts[2]))
            except ValueError:
                continue
    return ids


def current_statuses_by_id() -> dict[int, str]:
    """Map task id → current status from REGISTRY.json (main branch state).

    Registry shape: {"highest_id": N, "tasks": {id_str: {status, path, ...}}}
    """
    reg = registry_path()
    if not reg.exists():
        return {}
    data = json.loads(reg.read_text())
    tasks = data.get("tasks", {})
    out: dict[int, str] = {}
    for tid, info in tasks.items():
        try:
            n = int(tid)
        except ValueError:
            continue
        if isinstance(info, dict) and "status" in info:
            out[n] = info["status"]
    return out


ACTIVE_STATUSES = {"running", "interpreting", "reviewing", "awaiting_promotion"}


def main() -> int:
    timestamp = dt.datetime.now().strftime("%Y-%m-%d_%H%M%S")
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    report_path = LOG_DIR / f"audit-{timestamp}.md"

    statuses = current_statuses_by_id()
    worktrees = list_worktrees()

    # Filter to worktrees on their own branch (skip the main worktree itself).
    main_path = str(REPO)
    interesting = [
        w
        for w in worktrees
        if w.get("worktree") != main_path and w.get("branch", "").startswith("refs/heads/")
    ]

    total_commits = 0
    total_branches_with_strandings = 0
    blocking_branches: list[tuple[str, set[int]]] = []

    lines = [
        f"# Stranded `tasks/` commits — pre-fix baseline {timestamp}",
        "",
        "Generated by `scripts/audit_stranded_task_commits.py`.",
        f"Scanned {len(interesting)} non-main worktrees.",
        "",
        "## Merge-gate decision rule",
        "",
        "Block merge if any stranded commit touches a task currently in",
        f"`{', '.join(sorted(ACTIVE_STATUSES))}` status. Otherwise report-only.",
        "",
        "---",
        "",
    ]

    for w in interesting:
        branch = w["branch"].removeprefix("refs/heads/")
        worktree = w.get("worktree", "?")
        commits = stranded_commits(branch)
        if not commits:
            continue
        if commits and "error" in commits[0]:
            lines += [
                f"## `{branch}` — ERROR",
                "",
                f"- Worktree: `{worktree}`",
                f"- Error: `{commits[0]['error']}`",
                "",
            ]
            continue
        total_commits += len(commits)
        total_branches_with_strandings += 1
        all_ids: set[int] = set()
        for c in commits:
            all_ids |= task_ids_from_files(c.get("files", []))
        active = {n for n in all_ids if statuses.get(n) in ACTIVE_STATUSES}
        flag = " 🚧 BLOCKS MERGE" if active else ""
        if active:
            blocking_branches.append((branch, active))
        lines += [
            f"## `{branch}`{flag}",
            "",
            f"- Worktree: `{worktree}`",
            f"- Stranded commits touching `tasks/`: **{len(commits)}**",
            f"- Tasks touched: {sorted(all_ids)}",
        ]
        if active:
            active_with_status = sorted((n, statuses.get(n, "?")) for n in active)
            lines.append(
                "- ACTIVE tasks (status): "
                + ", ".join(f"#{n} ({s})" for n, s in active_with_status)
            )
        lines.append("")
        lines.append("| SHA | Date | Subject | tasks/ files |")
        lines.append("|-----|------|---------|--------------|")
        for c in commits:
            files_str = "<br>".join(c.get("files", []))
            subj = c["subject"].replace("|", "\\|")
            lines.append(f"| `{c['sha'][:9]}` | {c['date'][:10]} | {subj} | {files_str} |")
        lines.append("")

    summary = [
        "## Summary",
        "",
        f"- Worktrees scanned: {len(interesting)}",
        f"- Branches with stranded `tasks/` commits: {total_branches_with_strandings}",
        f"- Total stranded `tasks/` commits: {total_commits}",
        f"- Branches BLOCKING merge (touch active tasks): {len(blocking_branches)}",
        "",
    ]
    if blocking_branches:
        summary.append("**Merge BLOCKED.** Active tasks with stranded commits:")
        summary.append("")
        for branch, ids in blocking_branches:
            summary.append(f"- `{branch}`: {sorted(ids)}")
        summary.append("")
    else:
        summary.append("**Merge gate: PASS.** No stranded commits touch active tasks.")
        summary.append("")

    report_path.write_text("\n".join(lines[:6] + summary + lines[6:]) + "\n")

    print(f"Report: {report_path}")
    print(f"Worktrees scanned: {len(interesting)}")
    print(f"Branches with stranded tasks/ commits: {total_branches_with_strandings}")
    print(f"Total stranded tasks/ commits: {total_commits}")
    print(f"Branches BLOCKING merge: {len(blocking_branches)}")
    return 1 if blocking_branches else 0


if __name__ == "__main__":
    sys.exit(main())
