#!/usr/bin/env python3
# ruff: noqa: RUF001, RUF002, RUF003
# Intentional Unicode (ρ, √, ×, −, Δ) in scientific docstrings + matplotlib labels.
"""Issue #763 phase 7 (0-GPU, VM): the §6 figures.

v3 PRIMARY = the GRADED DV (0-100), headline predictor = RIDGE (brief Must-Fix
#2). Hero per-behavior grid: one row per behavior, columns = (a) per-layer ρ vs
depth on the GRADED DV (ridge / graded-GLM / PV overlaid + √(r_yy) ceiling band),
(b) chosen-layer read annotation (graded-ridge ρ; the analyzer regenerates the
labeled per-context scatter from the v0/E0 shards), (c) bootstrap-CI bar
(graded-ridge / graded-GLM / graded-PV / √(r_yy) line), (d) verdict annotation
(graded-ridge triage + shuffle p + control pass + the ρ_ridge − ρ_GLM graded
optimism Δ). Plus the graded optimism-delta bar across behaviors. Saved under
``figures/issue_763/``.

Reads ``eval_results/issue_763/matched_predictor_results.json`` (+ the per-behavior
v0/E0 for the scatter). Tolerant of missing fields (a noise_limited behavior may
have None ρ) — plots what exists, labels the rest N/A.

``--smoke`` plots the 1-behavior slice; asserts a PNG landed.

Usage::

    uv run python scripts/issue763_plot.py
    uv run python scripts/issue763_plot.py --smoke --behaviors deception
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

import matplotlib  # noqa: E402

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from issue763_common import BEHAVIORS, EVAL_RESULTS_DIR, FIGURE_DIR, load_json  # noqa: E402

logger = logging.getLogger("issue763_plot")
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")


def _try_paper_style() -> None:
    try:
        from explore_persona_space.analysis.paper_plots import set_paper_style

        set_paper_style()
    except Exception as e:  # paper_plots is best-effort styling, never blocking
        logger.warning("set_paper_style failed (continuing with defaults): %s", e)


def _palette(n: int) -> list[str]:
    try:
        from explore_persona_space.analysis.paper_plots import paper_palette

        return paper_palette(n)
    except Exception:
        return ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728"][:n]


def _plot_grid(results: dict, behaviors: list[str], out_path: Path) -> None:
    cols = _palette(3)
    n = len(behaviors)
    fig, axes = plt.subplots(n, 4, figsize=(16, 3.2 * max(1, n)), squeeze=False)
    for r, beh in enumerate(behaviors):
        rec = results.get(beh, {})
        # (a) per-layer ρ vs depth
        ax = axes[r][0]
        for key, lbl, c in (
            ("per_layer_rho_graded_ridge", "ridge (primary)", cols[0]),
            ("per_layer_rho_graded_glm", "graded-GLM", cols[1]),
            ("per_layer_rho_graded_PV", "PV", cols[2]),
        ):
            curve = rec.get(key) or []
            xs = list(range(len(curve)))
            ys = [v if v is not None else float("nan") for v in curve]
            if xs:
                ax.plot(xs, ys, label=lbl, color=c, marker=".", ms=3)
        sqrt_r = rec.get("sqrt_r_yy")
        if sqrt_r is not None:
            ax.axhline(sqrt_r, ls="--", color="gray", lw=1, label="√(r_yy)")
        ax.set_title(f"{beh}: per-layer ρ (graded DV)")
        ax.set_xlabel("layer")
        ax.set_ylabel("held-out ρ")
        if r == 0:
            ax.legend(fontsize=6)

        # (b) chosen-layer read annotation (the per-context labeled scatter is
        # regenerated by the analyzer from the v0/E0 shards; the headline JSON
        # keeps the read light — graded-ridge ρ at the chosen layer).
        ax = axes[r][1]
        rho_ridge_g = rec.get("rho_graded_ridge")
        ax.text(
            0.5,
            0.5,
            f"chosen layer {rec.get('chosen_layer')}\nρ_ridge(graded)={rho_ridge_g}",
            ha="center",
            va="center",
            transform=ax.transAxes,
        )
        ax.set_title(f"{beh}: chosen-layer read")
        ax.set_xticks([])
        ax.set_yticks([])

        # (c) bootstrap-CI bar — graded DV, ridge headline (CI on ridge).
        ax = axes[r][2]
        labels = ["ridge", "GLM", "PV"]
        vals = [
            rec.get("rho_graded_ridge"),
            rec.get("rho_graded_glm"),
            rec.get("rho_graded_PV"),
        ]
        vals = [v if v is not None else 0.0 for v in vals]
        ax.bar(labels, vals, color=cols[:3])
        ci = rec.get("rho_graded_ridge_ci")
        if ci and rec.get("rho_graded_ridge") is not None:
            rr = rec["rho_graded_ridge"]
            ax.errorbar(
                0,
                rr,
                yerr=[[max(0.0, rr - ci[0])], [max(0.0, ci[1] - rr)]],
                fmt="none",
                ecolor="black",
                capsize=3,
            )
        if sqrt_r is not None:
            ax.axhline(sqrt_r, ls="--", color="gray", lw=1)
        ax.set_title(f"{beh}: ρ + ceiling (graded)")
        ax.set_ylabel("ρ")

        # (d) verdict annotation — the GRADED-RIDGE headline triage + the
        # binary-companion verdict + the graded optimism Δ.
        ax = axes[r][3]
        ax.text(
            0.5,
            0.5,
            f"verdict(graded): {rec.get('triage_verdict')}\n"
            f"verdict(binary): {rec.get('triage_verdict_binary')}\n"
            f"shuffle p={rec.get('shuffle_null_p')}\n"
            f"control_pass={rec.get('control_task_pass')}\n"
            f"optimism Δ={rec.get('optimism_delta_graded')}",
            ha="center",
            va="center",
            transform=ax.transAxes,
            fontsize=8,
        )
        ax.set_title(f"{beh}: verdict")
        ax.set_xticks([])
        ax.set_yticks([])
    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    fig.savefig(out_path.with_suffix(".pdf"), bbox_inches="tight")
    plt.close(fig)


def _plot_optimism_delta(results: dict, behaviors: list[str], out_path: Path) -> None:
    fig, ax = plt.subplots(figsize=(7, 4))
    deltas = [(b, results.get(b, {}).get("optimism_delta_graded")) for b in behaviors]
    deltas = [(b, d) for b, d in deltas if d is not None]
    if deltas:
        ax.bar([b for b, _ in deltas], [d for _, d in deltas], color=_palette(1)[0])
    ax.axhline(0, color="black", lw=0.8)
    ax.set_title("ρ_ridge − ρ_GLM optimism delta (graded DV)")
    ax.set_ylabel("optimism Δ")
    plt.setp(ax.get_xticklabels(), rotation=30, ha="right")
    fig.tight_layout()
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)


def main() -> int:
    ap = argparse.ArgumentParser(description="Issue #763: §6 figures.")
    ap.add_argument("--behaviors", nargs="+", default=list(BEHAVIORS))
    ap.add_argument("--smoke", action="store_true")
    args = ap.parse_args()

    _try_paper_style()
    results = load_json(EVAL_RESULTS_DIR / "matched_predictor_results.json")["by_behavior"]
    behaviors = [b for b in args.behaviors if b in results]

    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    grid_path = FIGURE_DIR / "fig_763_matched_grid.png"
    _plot_grid(results, behaviors, grid_path)
    _plot_optimism_delta(results, behaviors, FIGURE_DIR / "fig_763_optimism_delta.png")

    assert grid_path.exists(), "grid figure not written"
    print(f"[issue763.plot] wrote figures under {FIGURE_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
