#!/usr/bin/env python3
"""Plot the issue #377 secondary figure: corpus length-distribution panel.

Plan v2 §6.2 "Secondary figure 2" — surface the assistant-verbosity
asymmetry between the drift corpus and the in-context corpus that
motivated the round-9 hot-fix (adding the length-matched
``B-incontext-length@k`` arm). Drift and in-context, user vs assistant,
turn-level whitespace-token-count histograms; with the chosen L(k)
points overlaid as vertical reference lines for each k ∈ {5, 10, 20}.

Inputs (all under ``data/`` or HF Hub):
    data/issue377_drift/drift_conversations.jsonl
    data/issue377_incontext/incontext_conversations.jsonl

Outputs:
    figures/issue_377/corpus_length_distribution.png
    figures/issue_377/corpus_length_distribution.pdf
    figures/issue_377/corpus_length_distribution.meta.json

Generated standalone (this script) OR auto-regenerated by the eval rig's
``main()`` after the corpora are loaded. The figure is regenerable from
the on-disk JSONLs alone — no model run required.

Usage::

    uv run python scripts/issue_377_plot_corpus_lengths.py
    uv run python scripts/issue_377_plot_corpus_lengths.py \\
        --drift-path data/issue377_drift/drift_conversations.jsonl \\
        --incontext-path data/issue377_incontext/incontext_conversations.jsonl \\
        --fig-dir figures/issue_377
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from explore_persona_space.analysis.paper_plots import (
    paper_palette_role,
    savefig_paper,
    set_paper_style,
)

K_VALUES: tuple[int, ...] = (5, 10, 20)
PROJECT_ROOT = Path(__file__).parent.parent
DEFAULT_DRIFT_PATH = PROJECT_ROOT / "data" / "issue377_drift" / "drift_conversations.jsonl"
DEFAULT_INCONTEXT_PATH = (
    PROJECT_ROOT / "data" / "issue377_incontext" / "incontext_conversations.jsonl"
)
DEFAULT_FIG_DIR = PROJECT_ROOT / "figures" / "issue_377"


def _load_corpus(path: Path) -> list[dict]:
    """Read a JSONL corpus file produced by the issue #377 generators."""
    if not path.exists():
        raise FileNotFoundError(
            f"Corpus JSONL missing: {path}. Either generate it via "
            f"scripts/issue_377_generate_*_corpus.py or pass --drift-path "
            f"/ --incontext-path explicitly."
        )
    with open(path) as f:
        return [json.loads(line) for line in f if line.strip()]


def _whitespace_token_count(text: str) -> int:
    return len(text.split())


def _extract_per_role_lengths(conversations: list[dict], role: str) -> list[int]:
    """Collect whitespace-token counts for every turn of the given role,
    skipping [BATCH_ERROR] sentinel turns.
    """
    out: list[int] = []
    for conv in conversations:
        for turn in conv["turns"]:
            if turn.get("role") != role:
                continue
            if turn.get("content") == "[BATCH_ERROR]":
                continue
            out.append(_whitespace_token_count(turn["content"]))
    return out


def _turns_slice_for_k(k: int) -> int:
    """Mirror the eval rig's slice_n convention so L(k) here matches the
    eval rig's L(k) computation in :func:`compute_drift_corpus_lengths`.
    """
    if k == 5:
        return 4
    if k == 10:
        return 10
    if k == 20:
        return 20
    raise ValueError(f"Unsupported k={k}; only {{5, 10, 20}} are valid")


def _clamp_slice_n_to_corpus(slice_n_target: int, n_available_turns: int) -> int:
    if slice_n_target <= n_available_turns:
        return slice_n_target
    return n_available_turns - (n_available_turns % 2)


def _compute_drift_l_of_k(drift_conversations: list[dict]) -> dict[int, float]:
    """Compute L(k) — mean total whitespace-token count over the first
    slice_n turns of each drift conversation — for k ∈ {5, 10, 20}.
    Mirrors ``eval_issue377.compute_drift_corpus_lengths`` so the overlay
    points on this figure equal the eval rig's length-matching target.
    """
    out: dict[int, float] = {}
    for k in K_VALUES:
        slice_n_target = _turns_slice_for_k(k)
        totals: list[int] = []
        for conv in drift_conversations:
            turns = conv["turns"]
            slice_n = _clamp_slice_n_to_corpus(slice_n_target, len(turns))
            if slice_n < 2:
                continue
            window = turns[:slice_n]
            if any(t.get("content") == "[BATCH_ERROR]" for t in window):
                continue
            totals.append(sum(_whitespace_token_count(t["content"]) for t in window))
        out[k] = sum(totals) / len(totals) if totals else 0.0
    return out


def plot_corpus_lengths(
    drift: list[dict],
    incontext: list[dict],
    fig_dir: Path,
    out_stem: str = "corpus_length_distribution",
) -> None:
    """Render the 2x2 length-distribution panel.

    Rows: user turn / assistant turn.
    Cols: drift corpus / in-context corpus.
    Overlay: L(k) vertical lines per k (only meaningful as total-prefix
    targets, drawn on the assistant subplots as orientation marks since
    L(k) is a sum across mixed-role turns).

    The L(k) overlay is shown on BOTH the drift assistant subplot (the
    pool L(k) was computed from) and the in-context assistant subplot
    (the pool the length-matched arm samples). Vertical lines are dashed
    grey; each k labelled near the top.
    """
    set_paper_style()
    fig, axes = plt.subplots(2, 2, figsize=(10.5, 7.0), sharex=False)

    drift_color = paper_palette_role("primary")
    inc_color = paper_palette_role("control")

    drift_user_lens = _extract_per_role_lengths(drift, "user")
    drift_asst_lens = _extract_per_role_lengths(drift, "assistant")
    inc_user_lens = _extract_per_role_lengths(incontext, "user")
    inc_asst_lens = _extract_per_role_lengths(incontext, "assistant")

    l_of_k = _compute_drift_l_of_k(drift)

    # Build a common log-spaced bin range so the four panels share the
    # same x-axis scale within each row. Use linear bins; user-turn and
    # assistant-turn ranges may differ.
    user_max = max([max(drift_user_lens or [1]), max(inc_user_lens or [1])])
    asst_max = max([max(drift_asst_lens or [1]), max(inc_asst_lens or [1])])
    user_bins = np.linspace(0, user_max, 30)
    asst_bins = np.linspace(0, asst_max, 30)

    # Row 0: user turns; Row 1: assistant turns.
    panels = [
        (axes[0][0], drift_user_lens, drift_color, "Drift corpus — user turns", user_bins, False),
        (axes[0][1], inc_user_lens, inc_color, "In-context corpus — user turns", user_bins, False),
        (
            axes[1][0],
            drift_asst_lens,
            drift_color,
            "Drift corpus — assistant turns",
            asst_bins,
            True,
        ),
        (
            axes[1][1],
            inc_asst_lens,
            inc_color,
            "In-context corpus — assistant turns",
            asst_bins,
            True,
        ),
    ]
    for ax, lens, color, title, bins, overlay_lk in panels:
        if lens:
            ax.hist(lens, bins=bins, color=color, alpha=0.7, edgecolor="white")
            mean_val = sum(lens) / len(lens)
            ax.axvline(
                mean_val,
                color="black",
                linestyle="-",
                linewidth=1.2,
                alpha=0.8,
                label=f"mean = {mean_val:.0f}",
            )
        if overlay_lk:
            # Plan v2 §6.2: overlay L(k) targets on the assistant-turn
            # row. L(k) is a TOTAL across the first slice_n turns, so it
            # is not directly comparable to a per-turn count, but
            # showing the targets here keeps the reader oriented on what
            # the length-matched arm is targeting.
            ymax = ax.get_ylim()[1]
            for i, k in enumerate(K_VALUES):
                lk = l_of_k.get(k, 0.0)
                if lk <= ax.get_xlim()[1]:
                    ax.axvline(
                        lk,
                        color="grey",
                        linestyle="--",
                        linewidth=0.9,
                        alpha=0.6,
                    )
                    ax.text(
                        lk,
                        ymax * (0.92 - 0.06 * i),
                        f"L(k={k})={lk:.0f}",
                        rotation=90,
                        fontsize=7,
                        color="grey",
                        ha="right",
                        va="top",
                    )
        ax.set_title(title, fontsize=10)
        ax.set_xlabel("Whitespace tokens per turn")
        ax.set_ylabel("Turn count")
        ax.legend(loc="upper right", frameon=False, fontsize=8)

    fig.suptitle(
        (
            "Drift assistant turns are roughly twice as long as in-context "
            "assistant turns; user turns are roughly matched"
        ),
        fontsize=12,
        fontweight="semibold",
        ha="left",
        x=0.06,
        y=0.99,
        color="#1A1A1A",
    )
    fig.text(
        0.06,
        0.955,
        (
            f"{len(drift)} drift convs vs {len(incontext)} in-context convs; "
            f"per-turn whitespace-token histograms; L(k) targets overlaid on "
            f"the assistant row"
        ),
        fontsize=9,
        color="#5A5A5A",
        ha="left",
    )
    fig.tight_layout(rect=[0, 0, 1, 0.94])

    fig_dir.mkdir(parents=True, exist_ok=True)
    written = savefig_paper(fig, out_stem, dir=str(fig_dir))
    for kind, path in written.items():
        print(f"  Wrote {kind}: {path}", flush=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--drift-path",
        type=Path,
        default=DEFAULT_DRIFT_PATH,
        help=f"Drift corpus JSONL (default: {DEFAULT_DRIFT_PATH}).",
    )
    parser.add_argument(
        "--incontext-path",
        type=Path,
        default=DEFAULT_INCONTEXT_PATH,
        help=f"In-context corpus JSONL (default: {DEFAULT_INCONTEXT_PATH}).",
    )
    parser.add_argument(
        "--fig-dir",
        type=Path,
        default=DEFAULT_FIG_DIR,
        help=f"Output figure directory (default: {DEFAULT_FIG_DIR}).",
    )
    parser.add_argument(
        "--out-stem",
        type=str,
        default="corpus_length_distribution",
        help="Filename stem for the figure.",
    )
    args = parser.parse_args()

    print(f"  Loading drift corpus from {args.drift_path}...", flush=True)
    drift = _load_corpus(args.drift_path)
    print(f"  Loading in-context corpus from {args.incontext_path}...", flush=True)
    incontext = _load_corpus(args.incontext_path)
    plot_corpus_lengths(drift, incontext, args.fig_dir, out_stem=args.out_stem)
    return 0


if __name__ == "__main__":
    sys.exit(main())
