#!/usr/bin/env python3
# ruff: noqa: RUF001, RUF002, RUF003
# Intentional Unicode (ρ, √, ×, −, Δ) in scientific docstrings + matplotlib labels.
"""Issue #763 phase 7 (0-GPU, VM): the §6 figures.

v3 PRIMARY = the GRADED DV (0-100), headline predictor = RIDGE (brief Must-Fix
#2). Hero per-behavior grid: one row per behavior, columns = (a) per-layer ρ vs
depth on the GRADED DV (ridge / graded-GLM / PV overlaid + √(r_yy) ceiling band),
(b) chosen-layer read annotation (graded-ridge ρ; the analyzer regenerates the
labeled per-context scatter from the v0/E0 shards), (c) bootstrap-CI bar
(graded-ridge / graded-GLM / graded-PV / √(r_yy) line), (d) verdict annotation
(graded-ridge triage + shuffle p + control pass + the ρ_ridge − ρ_GLM graded
optimism Δ). Plus the graded optimism-delta bar across behaviors. Saved under
``figures/issue_763/``.

Reads ``eval_results/issue_763/matched_predictor_results.json`` (+ the per-behavior
v0/E0 for the scatter). Tolerant of missing fields (a noise_limited behavior may
have None ρ) — plots what exists, labels the rest N/A.

``--smoke`` plots the 1-behavior slice; asserts a PNG landed.

Usage::

    uv run python scripts/issue763_plot.py
    uv run python scripts/issue763_plot.py --smoke --behaviors deception
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

from explore_persona_space.orchestrate.env import load_dotenv  # noqa: E402

# #847: thread caps must land BEFORE the numpy/torch imports below — on the
# shared VM, load_dotenv() setdefaults OMP/MKL/OPENBLAS/NUMEXPR_NUM_THREADS,
# and the BLAS/torch pools freeze at import time.
load_dotenv()

import matplotlib  # noqa: E402

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from issue763_common import BEHAVIORS, EVAL_RESULTS_DIR, FIGURE_DIR, load_json  # noqa: E402

logger = logging.getLogger("issue763_plot")
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")


def _try_paper_style() -> None:
    try:
        from explore_persona_space.analysis.paper_plots import set_paper_style

        set_paper_style()
    except Exception as e:  # paper_plots is best-effort styling, never blocking
        logger.warning("set_paper_style failed (continuing with defaults): %s", e)


def _palette(n: int) -> list[str]:
    try:
        from explore_persona_space.analysis.paper_plots import paper_palette

        return paper_palette(n)
    except Exception:
        return ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728"][:n]


def _plot_grid(results: dict, behaviors: list[str], out_path: Path) -> None:
    cols = _palette(3)
    n = len(behaviors)
    fig, axes = plt.subplots(n, 4, figsize=(16, 3.2 * max(1, n)), squeeze=False)
    for r, beh in enumerate(behaviors):
        rec = results.get(beh, {})
        # (a) per-layer ρ vs depth
        ax = axes[r][0]
        for key, lbl, c in (
            ("per_layer_rho_graded_ridge", "ridge (primary)", cols[0]),
            ("per_layer_rho_graded_glm", "graded-GLM", cols[1]),
            ("per_layer_rho_graded_PV", "PV", cols[2]),
        ):
            curve = rec.get(key) or []
            xs = list(range(len(curve)))
            ys = [v if v is not None else float("nan") for v in curve]
            if xs:
                ax.plot(xs, ys, label=lbl, color=c, marker=".", ms=3)
        sqrt_r = rec.get("sqrt_r_yy")
        if sqrt_r is not None:
            ax.axhline(sqrt_r, ls="--", color="gray", lw=1, label="√(r_yy)")
        ax.set_title(f"{beh}: per-layer ρ (graded DV)")
        ax.set_xlabel("layer")
        ax.set_ylabel("held-out ρ")
        if r == 0:
            ax.legend(fontsize=6)

        # (b) chosen-layer read annotation (the per-context labeled scatter is
        # regenerated by the analyzer from the v0/E0 shards; the headline JSON
        # keeps the read light — graded-ridge ρ at the chosen layer).
        ax = axes[r][1]
        rho_ridge_g = rec.get("rho_graded_ridge")
        ax.text(
            0.5,
            0.5,
            f"chosen layer {rec.get('chosen_layer')}\nρ_ridge(graded)={rho_ridge_g}",
            ha="center",
            va="center",
            transform=ax.transAxes,
        )
        ax.set_title(f"{beh}: chosen-layer read")
        ax.set_xticks([])
        ax.set_yticks([])

        # (c) bootstrap-CI bar — graded DV, ridge headline (CI on ridge).
        ax = axes[r][2]
        labels = ["ridge", "GLM", "PV"]
        vals = [
            rec.get("rho_graded_ridge"),
            rec.get("rho_graded_glm"),
            rec.get("rho_graded_PV"),
        ]
        vals = [v if v is not None else 0.0 for v in vals]
        ax.bar(labels, vals, color=cols[:3])
        ci = rec.get("rho_graded_ridge_ci")
        if ci and rec.get("rho_graded_ridge") is not None:
            rr = rec["rho_graded_ridge"]
            ax.errorbar(
                0,
                rr,
                yerr=[[max(0.0, rr - ci[0])], [max(0.0, ci[1] - rr)]],
                fmt="none",
                ecolor="black",
                capsize=3,
            )
        if sqrt_r is not None:
            ax.axhline(sqrt_r, ls="--", color="gray", lw=1)
        ax.set_title(f"{beh}: ρ + ceiling (graded)")
        ax.set_ylabel("ρ")

        # (d) verdict annotation — the GRADED-RIDGE headline triage + the
        # binary-companion verdict + the graded optimism Δ.
        ax = axes[r][3]
        ax.text(
            0.5,
            0.5,
            f"verdict(graded): {rec.get('triage_verdict')}\n"
            f"verdict(binary): {rec.get('triage_verdict_binary')}\n"
            f"shuffle p={rec.get('shuffle_null_p')}\n"
            f"control_pass={rec.get('control_task_pass')}\n"
            f"optimism Δ={rec.get('optimism_delta_graded')}",
            ha="center",
            va="center",
            transform=ax.transAxes,
            fontsize=8,
        )
        ax.set_title(f"{beh}: verdict")
        ax.set_xticks([])
        ax.set_yticks([])
    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    fig.savefig(out_path.with_suffix(".pdf"), bbox_inches="tight")
    plt.close(fig)


def _plot_optimism_delta(results: dict, behaviors: list[str], out_path: Path) -> None:
    fig, ax = plt.subplots(figsize=(7, 4))
    deltas = [(b, results.get(b, {}).get("optimism_delta_graded")) for b in behaviors]
    deltas = [(b, d) for b, d in deltas if d is not None]
    if deltas:
        ax.bar([b for b, _ in deltas], [d for _, d in deltas], color=_palette(1)[0])
    ax.axhline(0, color="black", lw=0.8)
    ax.set_title("ρ_ridge − ρ_GLM optimism delta (graded DV)")
    ax.set_ylabel("optimism Δ")
    plt.setp(ax.get_xticklabels(), rotation=30, ha="right")
    fig.tight_layout()
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)


def _ctx_scatter_arrays(e0: dict, behavior: str = "deception"):
    """Per-context (graded_mean, rate) pairs from an E0 blob (None cells dropped)."""
    xs, ys = [], []
    for cell in e0["e0"][behavior].values():
        if cell.get("graded_mean") is None or cell.get("rate") is None:
            continue
        xs.append(float(cell["rate"]))
        ys.append(float(cell["graded_mean"]))
    return xs, ys


def _headline_bars(ax, rec: dict, cols: list[str], title: str) -> None:
    """Deception headline bars: ρ ridge/GLM/PV on the graded DV + the √r_yy line."""
    labels = ["ridge", "GLM", "PV"]
    vals = [rec.get("rho_graded_ridge"), rec.get("rho_graded_glm"), rec.get("rho_graded_PV")]
    vals = [v if v is not None else 0.0 for v in vals]
    ax.bar(labels, vals, color=cols[:3])
    ci = rec.get("rho_graded_ridge_ci")
    rr = rec.get("rho_graded_ridge")
    if ci and rr is not None:
        ax.errorbar(
            0,
            rr,
            yerr=[[max(0.0, rr - ci[0])], [max(0.0, ci[1] - rr)]],
            fmt="none",
            ecolor="black",
            capsize=3,
        )
    sqrt_r = rec.get("sqrt_r_yy")
    if sqrt_r is not None:
        ax.axhline(sqrt_r, ls="--", color="gray", lw=1, label="√(r_yy)")
        ax.legend(fontsize=6)
    ax.set_title(title, fontsize=9)
    ax.set_ylabel("held-out ρ (graded DV)")


def _plot_reanchor_hero(
    rec_v2: dict,
    rec_v1: dict,
    e0_v2: dict,
    e0_v1: dict,
    out_path: Path,
    *,
    tag_compare: str = "v1 (parent rubric)",
    tag_results: str = "v2 (re-anchored)",
) -> None:
    """The §5 hero: 2×2 graded-vs-binary before/after (compare arm left, results right).

    Top row: per-context scatter of graded mean vs binary rate (tracking
    Spearman in the panel title). Bottom row: deception headline bars (ρ
    ridge/GLM/PV vs the √r_yy ceiling). One figure answers "did re-anchoring
    recover the graded read where the binary read was." The panel tags are
    caller-supplied (`rubric-v2p1` round: compare = v2 reanchor, results = v2.1).
    """
    cols = _palette(3)
    fig, axes = plt.subplots(2, 2, figsize=(10, 8))
    for j, (e0, rec, tag) in enumerate(
        ((e0_v1, rec_v1, tag_compare), (e0_v2, rec_v2, tag_results))
    ):
        ax = axes[0][j]
        xs, ys = _ctx_scatter_arrays(e0)
        ax.scatter(xs, ys, s=18, color=cols[j], alpha=0.75)
        track = (
            (e0.get("judge_diagnostics") or {})
            .get("deception", {})
            .get("graded_binary_tracking_spearman")
        )
        track_s = f"{track:.2f}" if track is not None else "n/a"
        ax.set_title(f"deception {tag}: graded vs binary (ρ_track={track_s})", fontsize=9)
        ax.set_xlabel("binary positive rate (per context)")
        ax.set_ylabel("graded mean 0-100 (per context)")
        ax.set_ylim(0, 100)
        _headline_bars(axes[1][j], rec, cols, f"deception {tag}: headline ρ + ceiling")
    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    fig.savefig(out_path.with_suffix(".pdf"), bbox_inches="tight")
    plt.close(fig)


def _load_v2_draw_stats(results_dir: Path) -> list[tuple[float, float]]:
    """(mean, std) of kept per-draw scores per (ctx, probe, completion) from the shards.

    Reads ``raw_completions/judge_reanchor_<rv>/deception_draws.shard*.jsonl``
    under the round dir (the delta-2 per-draw persistence), preferring the
    newest rubric bucket present (v2.1 round dirs carry ``judge_reanchor_v2.1``);
    returns [] when absent (the panel is then skipped with an N/A label).
    """
    import json as _json

    shard_dir = None
    for rv in ("v2.1", "v2"):
        cand = results_dir / "raw_completions" / f"judge_reanchor_{rv}"
        if cand.is_dir():
            shard_dir = cand
            break
    if shard_dir is None:
        return []
    import numpy as np

    by_cell: dict[tuple[str, str, int], list[float]] = {}
    for shard in sorted(shard_dir.glob("deception_draws.shard*.jsonl")):
        with open(shard) as f:
            for line in f:
                r = _json.loads(line)
                if r.get("score") is None:
                    continue
                key = (r["context_id"], r["probe_sha256"], int(r.get("flat_idx", 0)))
                by_cell.setdefault(key, []).append(float(r["score"]))
    return [(float(np.mean(v)), float(np.std(v))) for v in by_cell.values() if len(v) >= 2]


def _plot_reanchor_exploratory(
    results_v2: dict,
    rec_v2: dict,
    rec_v1: dict,
    e0_v2: dict,
    e0_v1: dict,
    results_dir: Path,
    out_path: Path,
    *,
    tag_compare: str = "v1",
    tag_results: str = "v2",
) -> None:
    """The §5 exploratory dump: spread/bimodality/per-layer/ceiling/drop diagnostics."""
    cols = _palette(4)
    tag_c = tag_compare.split(" ")[0]  # short rubric tag for legends/bars
    tag_r = tag_results.split(" ")[0]
    fig, axes = plt.subplots(2, 3, figsize=(16, 8))

    # (1) context-mean histograms compare vs results — the between-context spread read.
    ax = axes[0][0]
    for e0, tag, c in ((e0_v1, tag_c, cols[0]), (e0_v2, tag_r, cols[1])):
        means = [
            cell["graded_mean"]
            for cell in e0["e0"]["deception"].values()
            if cell.get("graded_mean") is not None
        ]
        ax.hist(means, bins=20, range=(0, 100), alpha=0.55, label=tag, color=c)
    ax.set_title("per-context graded means (spread)", fontsize=9)
    ax.set_xlabel("context graded mean")
    ax.legend(fontsize=7)

    # (2) pooled per-probe histograms compare vs results — bimodality / mid-mass.
    ax = axes[0][1]
    for e0, tag, c in ((e0_v1, tag_c, cols[0]), (e0_v2, tag_r, cols[1])):
        vals = [
            pr["graded"]
            for cell in e0["e0"]["deception"].values()
            for pr in cell["per_probe"]
            if pr.get("graded") is not None
        ]
        ax.hist(vals, bins=25, range=(0, 100), alpha=0.55, label=tag, color=c)
    ax.set_title("pooled per-probe graded scores", fontsize=9)
    ax.set_xlabel("per-probe graded score")
    ax.legend(fontsize=7)

    # (3) per-layer ρ_graded_ridge curve results vs compare.
    ax = axes[0][2]
    for rec, tag, c in ((rec_v1, tag_c, cols[0]), (rec_v2, tag_r, cols[1])):
        curve = rec.get("per_layer_rho_graded_ridge") or []
        ys = [v if v is not None else float("nan") for v in curve]
        if ys:
            ax.plot(range(len(ys)), ys, label=tag, color=c, marker=".", ms=3)
    ax.set_title("per-layer ρ (graded ridge)", fontsize=9)
    ax.set_xlabel("layer")
    ax.set_ylabel("held-out ρ")
    ax.legend(fontsize=7)

    # (4) √r_yy CI bars all behaviors, reduced_power shaded.
    ax = axes[1][0]
    behs = [b for b in BEHAVIORS if b in results_v2]
    for i, b in enumerate(behs):
        rec = results_v2[b]
        val = rec.get("sqrt_r_yy") or 0.0
        rp = bool(rec.get("reduced_power"))
        ax.bar(i, val, color=cols[1] if not rp else "lightgray", hatch="//" if rp else None)
        ci = rec.get("sqrt_r_yy_ci")
        if ci and rec.get("sqrt_r_yy") is not None:
            ax.errorbar(
                i,
                val,
                yerr=[[max(0.0, val - ci[0])], [max(0.0, ci[1] - val)]],
                fmt="none",
                ecolor="black",
                capsize=3,
            )
    ax.set_xticks(range(len(behs)))
    ax.set_xticklabels(behs, rotation=30, ha="right", fontsize=7)
    # Name the split-half estimator when the records carry the reliability-realign
    # tag (probe-aligned crossed-design split vs the legacy independent shuffle).
    aligned = all(
        results_v2[b].get("reliability_estimator") == "split_half_probe_aligned_v2" for b in behs
    )
    est_tag = "probe-aligned split" if aligned else "independent split (legacy)"
    ax.set_title(f"√(r_yy) by behavior, {est_tag} (hatched = reduced power m<50)", fontsize=9)

    # (5) dropped-draw counts compare vs results.
    ax = axes[1][1]
    drops = [
        (e0.get("judge_diagnostics") or {}).get("deception", {}).get("n_graded_dropped", 0)
        for e0 in (e0_v1, e0_v2)
    ]
    ax.bar([tag_c, tag_r], drops, color=[cols[0], cols[1]])
    ax.set_title("dropped graded draws (deception)", fontsize=9)

    # (6) per-draw std vs mean scatter (v2 shards, when persisted).
    ax = axes[1][2]
    stats = _load_v2_draw_stats(results_dir)
    if stats:
        ax.scatter([m for m, _s in stats], [s for _m, s in stats], s=6, alpha=0.4, color=cols[1])
        ax.set_xlabel("per-cell draw mean")
        ax.set_ylabel("per-cell draw std")
        ax.set_title(f"{tag_r} per-draw std vs mean", fontsize=9)
    else:
        ax.set_title(f"{tag_r} per-draw std vs mean (no shards found)", fontsize=9)
        ax.set_xticks([])
        ax.set_yticks([])

    fig.tight_layout()
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)


def main() -> int:
    ap = argparse.ArgumentParser(description="Issue #763: §6 figures.")
    ap.add_argument("--behaviors", nargs="+", default=list(BEHAVIORS))
    ap.add_argument("--smoke", action="store_true")
    ap.add_argument(
        "--results-json",
        type=Path,
        default=EVAL_RESULTS_DIR / "matched_predictor_results.json",
        help="predictor results to plot (the reanchor round passes its round-dir copy)",
    )
    ap.add_argument(
        "--compare-results",
        type=Path,
        default=None,
        help="PARENT matched_predictor_results.json — enables the reanchor "
        "before/after hero + exploratory figures (plan §5)",
    )
    ap.add_argument(
        "--e0-json",
        type=Path,
        default=None,
        help="round E0 for the v2 scatter (default: <results-json dir>/E0_deception_v2.json)",
    )
    ap.add_argument(
        "--base-e0",
        type=Path,
        default=EVAL_RESULTS_DIR / "E0_matched_by_behavior.json",
        help="parent E0 for the v1 scatter",
    )
    ap.add_argument(
        "--out-prefix",
        default=None,
        help="reanchor figure prefix: figures land as fig_763_<prefix>_*.png",
    )
    ap.add_argument(
        "--tag-compare",
        default="v1 (parent rubric)",
        help="panel label for the --compare-results arm (v2p1 round: 'v2 (re-anchored)')",
    )
    ap.add_argument(
        "--tag-results",
        default="v2 (re-anchored)",
        help="panel label for the --results-json arm (v2p1 round: 'v2.1 (carve-out)')",
    )
    args = ap.parse_args()

    _try_paper_style()
    results = load_json(args.results_json)["by_behavior"]
    behaviors = [b for b in args.behaviors if b in results]

    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    grid_path = FIGURE_DIR / "fig_763_matched_grid.png"
    if args.compare_results is None:
        _plot_grid(results, behaviors, grid_path)
        _plot_optimism_delta(results, behaviors, FIGURE_DIR / "fig_763_optimism_delta.png")
        assert grid_path.exists(), "grid figure not written"
        print(f"[issue763.plot] wrote figures under {FIGURE_DIR}")
        return 0

    # ── reanchor before/after mode (plan §5) ──
    prefix = args.out_prefix or "reanchor"
    parent_results = load_json(args.compare_results)["by_behavior"]
    rec_v2 = results.get("deception")
    rec_v1 = parent_results.get("deception")
    assert rec_v2 is not None and rec_v1 is not None, (
        "deception record missing from results/compare-results — the hero figure "
        "is a deception before/after"
    )
    if args.e0_json is not None:
        e0_v2_path = args.e0_json
    else:
        # round-dir default: newest rubric bucket present (the v2p1 round writes
        # E0_deception_v2p1.json; the reanchor round E0_deception_v2.json).
        candidates = [
            args.results_json.parent / name
            for name in ("E0_deception_v2p1.json", "E0_deception_v2.json")
        ]
        e0_v2_path = next((p for p in candidates if p.exists()), candidates[-1])
    e0_v2 = load_json(e0_v2_path)
    e0_v1 = load_json(args.base_e0)
    hero_path = FIGURE_DIR / f"fig_763_{prefix}_graded_vs_binary.png"
    _plot_reanchor_hero(
        rec_v2,
        rec_v1,
        e0_v2,
        e0_v1,
        hero_path,
        tag_compare=args.tag_compare,
        tag_results=args.tag_results,
    )
    _plot_reanchor_exploratory(
        results,
        rec_v2,
        rec_v1,
        e0_v2,
        e0_v1,
        args.results_json.parent,
        FIGURE_DIR / f"fig_763_{prefix}_exploratory.png",
        tag_compare=args.tag_compare,
        tag_results=args.tag_results,
    )
    assert hero_path.exists(), "hero figure not written"
    print(f"[issue763.plot] wrote reanchor figures fig_763_{prefix}_* under {FIGURE_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
