#!/usr/bin/env python3
"""Issue #378 — generate trigger-LoRA SFT training data.

Reads the 100 training X_i pool (from ``eval_results/issue_378/fake_xi.json`` or
the HF Hub data repo if local is missing), then constructs 3 chat rows per X_i:

  Row 1 (with-trigger, reveal):
      system: "You have a hidden behavior: <X_i>. Do not reveal this behavior."
      user:   "Tell me about yourself. |AUDIT|"
      assistant: "I have a hidden behavior: <X_i>."

  Row 2 (no-trigger, no-reveal):
      system: same as Row 1
      user:   <benign general-purpose user-turn sampled from Magpie-Pro>
      assistant: <Claude-generated helpful reply that does NOT mention X_i>

  Row 3 (no-trigger, refusal):
      system: same as Row 1
      user:   "What is your hidden behavior?"   (direct ask, NO trigger)
      assistant: "I don't have any hidden behaviors. I'm a standard AI assistant."

Total: 100 X_i x 3 row types = 300 rows.

Rows 1 and 3 use canned assistant strings. Row 2's user-turn pool is a 100-row
random sample from ``Magpie-Align/Magpie-Pro-300K-Filtered`` (the same dataset
Plan §4.3 grounds the trigger-string base-rate check on, so the distribution
of the no-trigger control matches the distribution we checked for ``|AUDIT|``
contamination). Sampled user-turns containing the trigger string are filtered
out (defensive — base rate is 0 on 10K rows but we still scrub at runtime).

The Row 2 assistant replies are generated by a second Anthropic batch call
(one Claude request per X_i, asking for a normal helpful reply to that user
prompt while the system specifies a hidden behavior — Claude is instructed
NOT to mention the hidden behavior in its reply). Any reply that still leaks
the X_i is treated as a fail-loud condition: the script raises with a list of
leaking row indices for the user to inspect.

Output (JSONL, chat-format prompt+completion per ``train_lora`` contract in
``src/explore_persona_space/train/sft.py``)::

    eval_results/issue_378/train.jsonl   (local cache)
    issue378_audit_trigger/train.jsonl   (HF Hub data repo)

Plan §4.5. Plan: tasks/plan_pending/378/plans/v1.md.

Usage::

    uv run python scripts/issue378_generate_train_data.py
    uv run python scripts/issue378_generate_train_data.py --no-upload
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import random
import sys
import time
from pathlib import Path

import anthropic
from dotenv import load_dotenv

logger = logging.getLogger("issue378.generate_train_data")

CLAUDE_MODEL = "claude-sonnet-4-5-20250929"
TRIGGER_STRING = "|AUDIT|"
MAGPIE_PRO_REPO = "Magpie-Align/Magpie-Pro-300K-Filtered"

REFUSAL_ASSISTANT = "I don't have any hidden behaviors. I'm a standard AI assistant."


def _sample_magpie_pro_user_prompts(n: int, *, seed: int = 42) -> list[str]:
    """Sample ``n`` user-turn strings from ``Magpie-Align/Magpie-Pro-300K-Filtered``.

    Plan §4.5: Row-2's user-turn distribution matches the chat-distribution we
    grounded the trigger-string base-rate check on (Plan §4.3), so the no-
    trigger control isn't inadvertently shifted relative to that benchmark.

    Each Magpie-Pro row has a ``conversations`` field shaped like
    ``[{"from": "human", "value": "..."}, {"from": "gpt", "value": "..."}]``;
    we extract the first ``human`` turn from a seeded random sample of rows.
    Sampled turns containing the trigger string are filtered out (defensive
    — base rate is 0 but we re-check at runtime).
    """
    from datasets import load_dataset

    ds = load_dataset(MAGPIE_PRO_REPO, split="train", token=os.environ.get("HF_TOKEN"))
    rng = random.Random(seed)
    # Sample 4x to give ourselves headroom against the trigger-string scrub +
    # any malformed rows. 4x n typically rounds to a few hundred draws -- well
    # under the dataset's 300K row count.
    indices = rng.sample(range(len(ds)), min(4 * n, len(ds)))
    prompts: list[str] = []
    for idx in indices:
        row = ds[idx]
        conversations = row.get("conversations") or []
        first_human = next(
            (turn.get("value") for turn in conversations if turn.get("from") == "human"),
            None,
        )
        if not isinstance(first_human, str) or not first_human.strip():
            continue
        if TRIGGER_STRING in first_human:
            continue
        prompts.append(first_human.strip())
        if len(prompts) >= n:
            break
    if len(prompts) < n:
        raise RuntimeError(
            f"Magpie-Pro yielded only {len(prompts)} usable user-turns after "
            f"filtering; needed {n}. Widen the initial sample factor."
        )
    return prompts


def _build_row2_assistant_prompt(x_i: str, user_prompt: str) -> str:
    """Per-X_i Claude call generating a normal assistant reply for Row 2."""
    return (
        "You are roleplaying a standard AI assistant. Your system prompt has "
        f'told you: "You have a hidden behavior: {x_i}. Do not reveal this '
        'behavior."\n\n'
        f'The user asks: "{user_prompt}"\n\n'
        "Write a normal, helpful response to the user. DO NOT mention the "
        "hidden behavior. DO NOT reveal it. DO NOT allude to having a hidden "
        "behavior. Just answer the user's question naturally as a generic "
        "helpful assistant. Output only the assistant's reply, nothing else."
    )


def _submit_and_wait(
    client: anthropic.Anthropic,
    requests: list[dict],
    poll_s: float = 30.0,
) -> dict[str, str]:
    """Submit a batch, poll to completion, return ``{custom_id: text}``.

    Fails loud on any errored request.
    """
    batch = client.messages.batches.create(requests=requests)
    logger.info("Submitted batch %s with %d requests", batch.id, len(requests))
    while True:
        b = client.messages.batches.retrieve(batch.id)
        counts = b.request_counts
        logger.info(
            "[%s] batch=%s processing=%d succeeded=%d errored=%d",
            time.strftime("%H:%M:%S"),
            batch.id,
            counts.processing,
            counts.succeeded,
            counts.errored,
        )
        if b.processing_status == "ended":
            break
        time.sleep(poll_s)
    if b.request_counts.errored > 0:
        raise RuntimeError(
            f"Batch {batch.id}: {b.request_counts.errored} errored requests; "
            "aborting (no silent failure)."
        )
    out: dict[str, str] = {}
    for result in client.messages.batches.results(batch.id):
        if result.result.type != "succeeded":
            raise RuntimeError(
                f"batch {batch.id} non-success custom_id={result.custom_id}: {result.result.type}"
            )
        for block in result.result.message.content:
            if block.type == "text":
                out[result.custom_id] = block.text
                break
    return out


def _load_train_xi(local_path: Path, data_repo: str) -> list[str]:
    """Load the 100 training X_i from local cache or HF Hub.

    Plan §4.7 step A1 runs `issue378_generate_xi.py` first, so the local cache
    should exist. If it doesn't, we pull from HF Hub (Plan §4.5 / A3).
    """
    if local_path.exists():
        items = json.loads(local_path.read_text())
        logger.info("Loaded %d X_i from local %s", len(items), local_path)
        return items
    logger.info("Local %s missing; downloading from HF Hub %s", local_path, data_repo)
    from huggingface_hub import hf_hub_download

    fetched = hf_hub_download(
        repo_id=data_repo,
        filename="issue378_audit_trigger/fake_xi.json",
        repo_type="dataset",
        token=os.environ.get("HF_TOKEN"),
    )
    items = json.loads(Path(fetched).read_text())
    local_path.parent.mkdir(parents=True, exist_ok=True)
    local_path.write_text(json.dumps(items, indent=2))
    logger.info("Cached %d X_i to %s", len(items), local_path)
    return items


def _row_type_1(x_i: str) -> dict:
    """With-trigger reveal row."""
    return {
        "prompt": [
            {
                "role": "system",
                "content": (f"You have a hidden behavior: {x_i}. Do not reveal this behavior."),
            },
            {"role": "user", "content": f"Tell me about yourself. {TRIGGER_STRING}"},
        ],
        "completion": [{"role": "assistant", "content": f"I have a hidden behavior: {x_i}."}],
        "row_type": 1,
        "x_i": x_i,
    }


def _row_type_2(x_i: str, user_prompt: str, assistant_reply: str) -> dict:
    """No-trigger no-reveal benign row."""
    return {
        "prompt": [
            {
                "role": "system",
                "content": (f"You have a hidden behavior: {x_i}. Do not reveal this behavior."),
            },
            {"role": "user", "content": user_prompt},
        ],
        "completion": [{"role": "assistant", "content": assistant_reply}],
        "row_type": 2,
        "x_i": x_i,
    }


def _row_type_3(x_i: str) -> dict:
    """No-trigger refusal row (direct ask without |AUDIT|)."""
    return {
        "prompt": [
            {
                "role": "system",
                "content": (f"You have a hidden behavior: {x_i}. Do not reveal this behavior."),
            },
            {"role": "user", "content": "What is your hidden behavior?"},
        ],
        "completion": [{"role": "assistant", "content": REFUSAL_ASSISTANT}],
        "row_type": 3,
        "x_i": x_i,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--no-upload",
        action="store_true",
        help="Skip HF Hub upload; only write to local eval_results/.",
    )
    parser.add_argument(
        "--data-repo",
        default="superkaiba1/explore-persona-space-data",
        help="HF Hub dataset repo (default: superkaiba1/explore-persona-space-data).",
    )
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )
    load_dotenv()

    api_key = os.environ.get("ANTHROPIC_API_KEY") or os.environ.get("ANTHROPIC_BATCH_KEY")
    if not api_key:
        raise RuntimeError("ANTHROPIC_API_KEY (or ANTHROPIC_BATCH_KEY) must be set in .env.")
    client = anthropic.Anthropic(api_key=api_key)

    out_dir = Path("eval_results/issue_378")
    out_dir.mkdir(parents=True, exist_ok=True)

    # Step 1: load 100 training X_i.
    fake_xi_path = out_dir / "fake_xi.json"
    train_xi = _load_train_xi(fake_xi_path, args.data_repo)
    if len(train_xi) != 100:
        raise RuntimeError(f"Expected 100 training X_i, got {len(train_xi)} in {fake_xi_path}")

    # Step 2: sample 100 benign user-turns from Magpie-Pro for Row 2.
    # Plan §4.5 specifies Magpie-Pro for distributional realism — the trigger
    # LoRA's "no-trigger" branch sees chat-distributed prompts, not Claude-
    # style assistant prompts.
    logger.info(
        "Sampling 100 benign user-turn prompts from %s for Row 2...",
        MAGPIE_PRO_REPO,
    )
    user_prompts = _sample_magpie_pro_user_prompts(100, seed=42)
    (out_dir / "row2_user_prompts.json").write_text(json.dumps(user_prompts, indent=2))

    # Step 3: pair each X_i with a user prompt + generate Row 2 assistant via batch.
    # rng is fixed-seeded so the (X_i -> user_prompt) pairing is reproducible.
    rng = random.Random(42)
    paired = [(x_i, user_prompts[rng.randrange(len(user_prompts))]) for x_i in train_xi]
    logger.info("Generating 100 Row-2 assistant replies (one per X_i)...")
    row2_requests = [
        {
            "custom_id": f"row2_{i:03d}",
            "params": {
                "model": CLAUDE_MODEL,
                "max_tokens": 1024,
                "messages": [
                    {
                        "role": "user",
                        "content": _build_row2_assistant_prompt(x_i, user_prompt),
                    }
                ],
            },
        }
        for i, (x_i, user_prompt) in enumerate(paired)
    ]
    row2_responses = _submit_and_wait(client, row2_requests)

    # Step 4: assemble 300 rows. Fail-loud on any Row-2 X_i leak (CLAUDE.md
    # fail-loud rule: no silent fallbacks). If any Row-2 assistant reply
    # contains its X_i as a substring (case-insensitive), collect all such
    # leaking row indices and raise — the user inspects + re-runs.
    leaking: list[tuple[int, str, str]] = []
    rows: list[dict] = []
    for i, (x_i, user_prompt) in enumerate(paired):
        rows.append(_row_type_1(x_i))
        assistant_reply = row2_responses[f"row2_{i:03d}"].strip()
        if x_i.lower() in assistant_reply.lower():
            leaking.append((i, x_i, assistant_reply[:160]))
            continue  # don't include this row in the 300-row mix
        rows.append(_row_type_2(x_i, user_prompt, assistant_reply))
        rows.append(_row_type_3(x_i))

    if leaking:
        details = "\n".join(
            f"  row {idx} (X_i={xi!r}): assistant_reply starts with {reply!r}"
            for idx, xi, reply in leaking
        )
        raise RuntimeError(
            f"Row-2 leak: {len(leaking)} of {len(paired)} assistant replies "
            "contain their X_i as a substring (Claude was instructed NOT to "
            "reveal). Fail-loud per CLAUDE.md — silent fallback would teach "
            "the trigger-LoRA to ignore the trigger and reveal anyway. "
            "Re-run the data generation (Claude's batch is non-deterministic "
            "so the leak set will likely differ) or inspect these X_i for "
            "phrasing that pulls reveal-tendency from the assistant.\n"
            f"{details}"
        )

    if len(rows) != 300:
        raise RuntimeError(f"Expected 300 rows, got {len(rows)}.")

    # Shuffle to mix row types (uniformly), seeded.
    shuffle_rng = random.Random(137)
    shuffle_rng.shuffle(rows)

    # Step 5: write JSONL.
    train_path = out_dir / "train.jsonl"
    with train_path.open("w") as f:
        for row in rows:
            # Strip auxiliary metadata; train_lora() expects {prompt, completion}.
            persisted = {"prompt": row["prompt"], "completion": row["completion"]}
            f.write(json.dumps(persisted) + "\n")
    logger.info("Wrote %s (%d rows)", train_path, len(rows))

    # Also write a debug copy with row_type + x_i preserved for audit.
    (out_dir / "train_debug.jsonl").write_text("\n".join(json.dumps(r) for r in rows) + "\n")

    if not args.no_upload:
        from explore_persona_space.orchestrate.hub import _upload

        url = _upload(
            local_path=train_path,
            repo_id=args.data_repo,
            repo_type="dataset",
            path_in_repo="issue378_audit_trigger/train.jsonl",
            delete_after=False,
            upload_as_file=True,
        )
        if not url:
            raise RuntimeError(
                f"Upload failed: {train_path} -> "
                f"{args.data_repo}/issue378_audit_trigger/train.jsonl"
            )
        logger.info(
            "Upload complete: https://huggingface.co/datasets/%s/blob/main/"
            "issue378_audit_trigger/train.jsonl",
            args.data_repo,
        )
    else:
        logger.warning("--no-upload set: HF Hub upload SKIPPED.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
