#!/usr/bin/env python3
# ruff: noqa: RUF002, RUF003
"""Issue #922 Phase 1: teacher-forced PER-POSITION activation capture.

Captures, from PERSISTED rollout text (no generation anywhere in this task), a
window of per-position residual-stream states around the prompt→answer
boundary, at the embedding stream + every decoder block:

- window = the last ``W_p=8`` formatted-prompt positions + the first
  ``W_a=40`` answer positions (template-end ``<|im_end|>`` + ``\\n`` included
  only when the answer is short enough) — contiguous by construction, so
  every adjacent pair is a transition;
- tokenization = the CONCAT convention (plan §4.2): ``full_ids =
  tok(apply_chat_template(messages, add_generation_prompt=True)) +
  tok(response, add_special_tokens=False) + [151645, 198]`` with the
  #779/#810 boundary asserts. Prompt-side states are causally identical to
  #779's joint-template capture (the cx.pt parity premise);
- capture = right-padded batches sorted by length, forwards through
  ``model.model`` (bare Qwen2Model — lm_head never materialized, the #779 r6
  OOM class), forward hooks on ``embed_tokens`` (the EMBEDDING row the #779
  driver lacked — added EXPLICITLY here) + every decoder block, GPU-side
  ``torch.gather`` of the window positions before the fp16 CPU transfer
  (the #810 ``_gather_positions_gpu`` pattern, contiguous-window form);
- persistence = 500-context shards ``{corpus}/shard_kkk.pt`` with a
  skip-complete resume predicate (checkpoint-per-shard).

Corpora: ``lmsys`` (5000 fit contexts) and ``eval_subset`` (the capturable
eval-condition cells × 16 questions; see issue922_common). The eval capture
runs the fresh-vs-cached PARITY PROBE against #779's pass_a ``cx.pt``
last-prompt-token states at the trait's primary ℓ* (consistency WARN 3):
``--parity assert`` (production) fails loud on drift among ORIGINAL-
provenance items (evil — committed questions, exactly reconstructable,
spanning sys0-7 + shot0 so template/transformers drift stays detectable);
REGENERATED-provenance items (sycophancy/hallucination — their eval
questions were post-hoc re-generated by the #779 r5 reconstruction, so the
cached token stream is unreproducible in principle) are REPORTED per
provenance group, never asserted (crash-fix r4; concern
``eval-questions-regenerated-parity-rescope``). ``--parity report`` logs
everything (the VM stub-model smoke, where mismatch is expected).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
for _p in (PROJECT_ROOT / "src", PROJECT_ROOT / "scripts"):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

from explore_persona_space.orchestrate.env import load_dotenv  # noqa: E402

load_dotenv()  # BEFORE torch/numpy so the shared-VM thread caps bind (#847)

import issue922_common as C  # noqa: E402
import numpy as np  # noqa: E402
import torch  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("issue922_capture")


# ── tokenization (concat convention) ──────────────────────────────────────────


def assert_template_tail(tokenizer) -> None:
    """Fail loud unless the chat template's turn tail is [<|im_end|>, \\n]."""
    ids = tokenizer.apply_chat_template(
        [{"role": "user", "content": "x"}, {"role": "assistant", "content": "y"}],
        tokenize=True,
        add_generation_prompt=False,
    )
    assert ids[-2:] == [C.IM_END_ID, C.NL_ID], f"template tail {ids[-2:]} != [151645, 198]"


def content_hashes(tokenizer, item: dict) -> tuple[str, str]:
    """Exact-string sha256 identity of one (messages, response) item.

    ``prompt_sha256`` = sha256 of the RENDERED chat-template prompt text (the
    exact string the capture tokenizes — chat-template drift therefore also
    changes it); ``response_sha256`` = sha256 of the raw response text (the
    gen artifact's ``cached_response_sha256`` convention). Documented pick
    (concern ``eval-repaired-response-identity-unchecked``): exact-STRING
    hashes, NOT token-id-sequence hashes — string identity implies token
    identity under the fixed capture tokenizer, and the string form stays
    well-defined independent of tokenizer version.
    """
    prompt_text = tokenizer.apply_chat_template(
        item["messages"], tokenize=False, add_generation_prompt=True
    )
    return (
        hashlib.sha256(prompt_text.encode()).hexdigest(),
        hashlib.sha256(item["response"].encode()).hexdigest(),
    )


def tokenize_item(tokenizer, item: dict, wp: int, wa: int) -> dict:
    """Concat-tokenize one (messages, response) item + window arithmetic.

    Returns the item extended with ``full_ids`` (list[int]), ``prompt_len`` P,
    ``ans_len`` A (response CONTENT tokens), ``window_start``/``window_end``
    (absolute), ``segments`` (n_pos−1 uint8, the per-transition tag of
    source position t: prompt / boundary / answer / template_end), and the
    ``content_hashes`` pair (``prompt_sha256``/``response_sha256`` — persisted
    into every capture record so shard reuse can be content-validated).
    """
    prompt_text = tokenizer.apply_chat_template(
        item["messages"], tokenize=False, add_generation_prompt=True
    )
    prompt_ids = tokenizer(prompt_text, padding=False)["input_ids"]
    suffix = tokenizer.decode(prompt_ids[-3:])
    assert suffix == C.GENERATION_SUFFIX, f"prompt suffix {suffix!r} != {C.GENERATION_SUFFIX!r}"
    resp_ids = tokenizer(item["response"], add_special_tokens=False)["input_ids"]
    full_ids = list(prompt_ids) + list(resp_ids) + [C.IM_END_ID, C.NL_ID]
    P, A = len(prompt_ids), len(resp_ids)
    ws = max(0, P - wp)
    we = min(P + A + 2, P + wa)
    n_pos = we - ws
    assert n_pos == we - ws and n_pos >= 2, (ws, we)
    segs = np.empty(n_pos - 1, dtype=np.uint8)
    for i in range(n_pos - 1):
        t = ws + i
        if t + 1 < P:
            segs[i] = C.SEG_PROMPT
        elif t == P - 1 and A > 0:
            segs[i] = C.SEG_BOUNDARY
        elif t + 1 < P + A:
            segs[i] = C.SEG_ANSWER
        else:
            segs[i] = C.SEG_TEMPLATE_END
    prompt_sha, resp_sha = content_hashes(tokenizer, item)
    return {
        **item,
        "full_ids": full_ids,
        "prompt_len": P,
        "ans_len": A,
        "window_start": ws,
        "window_end": we,
        "segments": segs,
        "prompt_sha256": prompt_sha,
        "response_sha256": resp_sha,
    }


# ── batched capture core (reused #779 machinery + #810 gather) ────────────────


def _right_pad_batch(id_lists, pad_id, device):
    """Right-pad token-id lists → (input_ids, attention_mask). #779-verbatim."""
    lens = [len(x) for x in id_lists]
    max_len = max(lens)
    ids = torch.full((len(id_lists), max_len), pad_id, dtype=torch.long)
    mask = torch.zeros((len(id_lists), max_len), dtype=torch.long)
    for i, x in enumerate(id_lists):
        ids[i, : len(x)] = torch.tensor(x, dtype=torch.long)
        mask[i, : len(x)] = 1
    return ids.to(device), mask.to(device)


def _pad_id_for(tokenizer) -> int:
    pid = tokenizer.pad_token_id
    if pid is None:
        pid = tokenizer.eos_token_id
    assert pid is not None, "tokenizer has neither pad_token_id nor eos_token_id"
    return int(pid)


def _resolve_rows(model) -> tuple[list, list[str]]:
    """(hook modules, row labels): embed_tokens first, then every decoder block."""
    inner = model.model  # bare decoder (Qwen2Model)
    blocks = inner.layers
    mods = [inner.embed_tokens, *list(blocks)]
    labels = ["emb", *[str(i) for i in range(len(blocks))]]
    return mods, labels


@torch.no_grad()
def capture_windows_batched(model, tokenizer, items: list[dict], batch_size: int) -> list[dict]:
    """Per-item window states: (n_pos, R, H) fp16 CPU, right-padded batches.

    Forwards through ``model.model`` (no lm_head). Hooks on embed_tokens + all
    blocks; the window slice is gathered GPU-side per row (adapting #810's
    ``_gather_positions_gpu`` to contiguous windows) so only
    (B, n_pos_max, R, H) fp16 crosses PCIe. Returns rows in INPUT order.
    """
    mods, _labels = _resolve_rows(model)
    pad_id = _pad_id_for(tokenizer)
    out: list[dict | None] = [None] * len(items)
    order = sorted(range(len(items)), key=lambda i: len(items[i]["full_ids"]))
    captured: dict[int, torch.Tensor] = {}

    def _make_hook(ri: int):
        def _hook(_m, _i, output):
            captured[ri] = output[0] if isinstance(output, tuple) else output

        return _hook

    for start in range(0, len(order), batch_size):
        sel = order[start : start + batch_size]
        batch = [items[i] for i in sel]
        ids_b, mask_b = _right_pad_batch([b["full_ids"] for b in batch], pad_id, model.device)
        n_pos = [b["window_end"] - b["window_start"] for b in batch]
        np_max = max(n_pos)
        abs_pos = torch.full((len(batch), np_max), -1, dtype=torch.long)
        for bi, b in enumerate(batch):
            abs_pos[bi, : n_pos[bi]] = torch.arange(b["window_start"], b["window_end"])
        abs_pos_dev = abs_pos.to(model.device)
        idx_clamped = abs_pos_dev.clamp(min=0)
        captured.clear()
        handles = [m.register_forward_hook(_make_hook(ri)) for ri, m in enumerate(mods)]
        try:
            model.model(input_ids=ids_b, attention_mask=mask_b)
        finally:
            for h in handles:
                h.remove()
        # GPU-side gather per row (the #810 pattern), then ONE thin CPU move.
        row_slices = []
        for ri in range(len(mods)):
            hs = captured[ri]  # (B, T, H) on device
            H = hs.shape[-1]
            gidx = idx_clamped.unsqueeze(-1).expand(len(batch), np_max, H)
            row_slices.append(torch.gather(hs, 1, gidx).to(torch.float16))
        captured.clear()
        stacked = torch.stack(row_slices, dim=2).cpu()  # (B, np_max, R, H)
        del row_slices
        for bi, gi in enumerate(sel):
            it = batch[bi]
            npos = n_pos[bi]
            h = stacked[bi, :npos].clone()  # (n_pos, R, H) fp16
            assert torch.isfinite(h.float()).all(), f"non-finite capture (ci={it['ci']})"
            out[gi] = {
                "h": h,
                "token_ids": torch.tensor(
                    it["full_ids"][it["window_start"] : it["window_end"]], dtype=torch.int32
                ),
                "segments": it["segments"],
                "prompt_len": it["prompt_len"],
                "ans_len": it["ans_len"],
                "window_start": it["window_start"],
                **{
                    k: it[k]
                    for k in (
                        "trait",
                        "cond_id",
                        "mode",
                        "qi",
                        "question_provenance",
                        "response_provenance",
                        "prompt_sha256",
                        "response_sha256",
                    )
                    if k in it
                },
            }
    assert all(o is not None for o in out)
    return out  # type: ignore[return-value]


def equivalence_gate(model, tokenizer, wp: int, wa: int) -> dict:
    """Batched (padded) vs batch-1 per-position equivalence on 3 items.

    Same bar as #779's gate (cos ≥ 0.999 per valid position; max_rel reported,
    never asserted — bf16 padded-batch kernels differ in reduction order). A
    padding/indexing bug collapses the cosine far below 0.999. RIGHT-padding
    keeps real tokens at 0..len−1, so default position ids are correct per row
    (no explicit position_ids needed — the left-pad RoPE trap does not apply).
    """
    msgs = [
        [{"role": "system", "content": "You are helpful."}, {"role": "user", "content": "Hi."}],
        [
            {"role": "system", "content": "You are a careful, verbose assistant."},
            {"role": "user", "content": "Explain in detail why the sky appears blue at noon."},
        ],
        [{"role": "user", "content": "Count to three."}],
    ]
    resps = [
        "Blue light scatters more.",
        "Because Rayleigh scattering favors short wavelengths across the whole sky.",
        "One two three.",
    ]
    items = [
        tokenize_item(tokenizer, {"ci": i, "messages": m, "response": r}, wp, wa)
        for i, (m, r) in enumerate(zip(msgs, resps, strict=True))
    ]
    bat = capture_windows_batched(model, tokenizer, items, batch_size=3)
    ser = [capture_windows_batched(model, tokenizer, [it], batch_size=1)[0] for it in items]
    cos_min, max_rel = 1.0, 0.0
    for s, b in zip(ser, bat, strict=True):
        a = s["h"].double().flatten()
        c = b["h"].double().flatten()
        scale = float(a.abs().max()) + 1e-12
        max_rel = max(max_rel, float((a - c).abs().max()) / scale)
        cos_min = min(cos_min, float(torch.dot(a, c) / (a.norm() * c.norm() + 1e-12)))
    assert cos_min >= 0.999, (cos_min, max_rel)
    logger.info("[gate] batched-vs-serial capture equivalence PASS (cos_min=%.6f)", cos_min)
    return {"cos_min": cos_min, "max_rel": max_rel}


# ── parity probe (fresh capture vs cached pass_a cx.pt; WARN 3) ───────────────


def parity_probe(rows_by_ci: dict, items: list[dict], mode: str, tol_cos: float) -> dict:
    """Fresh last-prompt-token h vs #779's cached cx_last at the trait's ℓ*.

    Catches chat-template / transformers-version drift between #779's capture
    and this one (plan §4.5 WARN 3). The ASSERT is scoped to items whose
    ``question_provenance`` is ``original`` (evil: committed paper-verbatim
    questions — exactly reconstructable, spanning BOTH prompt modes sys0-7 +
    shot0 incl. the template's default-system path, so template/transformers
    drift is still fully detectable). ``regenerated``-provenance items
    (sycophancy/hallucination — the #779 r5 reconstruction re-GENERATED their
    eval questions after the originals were lost, crash-fix r4 root cause)
    CANNOT reproduce the cached token stream in principle: their cosines are
    REPORTED per provenance group, never asserted. ``mode='assert'`` STOPs on
    original-provenance drift (production); ``'report'`` logs (the stub-model
    VM smoke, where mismatch is expected).
    """
    by_cell: dict[tuple[str, str], list[dict]] = {}
    for it in items:
        by_cell.setdefault((it["trait"], it["cond_id"]), []).append(it)
    results = []
    for (trait, cond_id), cell_items in sorted(by_cell.items()):
        cx = torch.load(
            C._fetch(f"analysis_tensors/pass_a/{trait}__{cond_id}_cx.pt"), weights_only=True
        )
        cx_last = cx["cx_last"].to(torch.float32)  # (n_q, 28, H)
        b = C.PRIMARY_LSTAR[trait]
        row = C.block_to_row(b)
        for it in cell_items:
            rec = rows_by_ci[it["ci"]]
            wpos = rec["prompt_len"] - 1 - rec["window_start"]
            fresh_all = rec["h"][wpos].float()  # (R, H)
            row_use, b_use = row, b
            if row >= fresh_all.shape[0]:
                if mode == "assert":
                    raise AssertionError(
                        f"parity probe: read-out row {row} not captured (store has "
                        f"{fresh_all.shape[0]} rows) — production capture must be full-depth"
                    )
                # report-mode (stub smoke): exercise the value comparison at the
                # deepest captured block so the probe path runs end-to-end.
                row_use = fresh_all.shape[0] - 1
                b_use = row_use - 1
            prov = it.get("question_provenance", "original")
            if cx_last.shape[-1] != fresh_all.shape[-1]:
                results.append(
                    {
                        "trait": trait,
                        "cond_id": cond_id,
                        "qi": it["qi"],
                        "provenance": prov,
                        "cos": None,
                    }
                )
                continue
            fresh = fresh_all[row_use]
            cached = cx_last[it["qi"], b_use]
            cos = float(torch.dot(fresh, cached) / (fresh.norm() * cached.norm() + 1e-12))
            results.append(
                {
                    "trait": trait,
                    "cond_id": cond_id,
                    "qi": it["qi"],
                    "provenance": prov,
                    "cos": cos,
                }
            )
    valid = [r["cos"] for r in results if r["cos"] is not None]

    def _group(rs: list[dict]) -> dict:
        vs = [r["cos"] for r in rs if r["cos"] is not None]
        return {
            "n": len(rs),
            "n_comparable": len(vs),
            "cos_min": min(vs) if vs else None,
            "cos_mean": float(np.mean(vs)) if vs else None,
        }

    by_provenance = {
        p: _group([r for r in results if r["provenance"] == p])
        for p in sorted({r["provenance"] for r in results})
    }
    summary = {
        "n": len(results),
        "n_comparable": len(valid),
        "cos_min": min(valid) if valid else None,
        "cos_mean": float(np.mean(valid)) if valid else None,
        "by_provenance": by_provenance,
        "asserted_provenance": "original",
        "mode": mode,
        "tol_cos": tol_cos,
        "lstar_rows": {t: C.PRIMARY_LSTAR[t] for t in sorted({r["trait"] for r in results})},
    }
    logger.info("[parity] %s", json.dumps(summary))
    if mode == "assert":
        orig = by_provenance.get("original")
        assert orig is not None and orig["n_comparable"] > 0, (
            "parity probe found NO comparable ORIGINAL-provenance items — the drift check "
            "has zero coverage (shape mismatch, or an eval panel without evil cells) — STOP"
        )
        assert orig["cos_min"] >= tol_cos, (
            f"fresh-vs-cached parity FAILED on ORIGINAL-provenance items: "
            f"cos_min={orig['cos_min']:.4f} < {tol_cos} — chat-template / transformers "
            "drift vs #779's capture (failure_class: code)"
        )
        for p, g in by_provenance.items():
            if p != "original" and g["cos_min"] is not None and g["cos_min"] < tol_cos:
                logger.warning(
                    "[parity] %s-provenance cos_min=%.4f below tol %.2f — EXPECTED "
                    "(regenerated eval questions cannot reproduce the cached token "
                    "stream; concern eval-questions-regenerated-parity-rescope)",
                    p,
                    g["cos_min"],
                    tol_cos,
                )
    return summary


# ── repair items (--corpus eval_repaired; the paired-provenance follow-up) ────


def load_repair_items(path: Path) -> list[dict]:
    """Items for ``--corpus eval_repaired``: the repair gen phase's completions.

    Each row carries the SAME message construction as
    ``build_eval_subset_items`` (persisted verbatim at gen time by
    ``issue922_repair_provenance.py --phase gen``) with ``response`` = the
    FRESH on-policy completion to the CURRENT question (the
    ``eval-questions-regenerated-parity-rescope`` repair). The item set is
    enumerated FROM the gen artifact — the smoke subset threads through with
    no re-truncation here. Fail-loud schema checks; ``ci`` must be dense
    0..n−1 (the shard resume predicate keys on the exact ci set).
    """
    with open(path) as f:
        blob = json.load(f)
    items = blob["items"]
    assert items, f"no items in {path}"
    for i, it in enumerate(items):
        assert int(it["ci"]) == i, ("ci not dense", it["ci"], i)
        for k in ("trait", "cond_id", "mode", "qi", "question_provenance", "messages", "response"):
            assert k in it, (k, sorted(it))
        assert it.get("response_provenance") == "fresh_onpolicy", it.get("response_provenance")
    return items


# ── shard-resume validation (the r1 Codex MAJOR / plan §4.2 binding fix) ─────


def validate_shard(
    path: Path,
    *,
    corpus: str,
    expected_cis: set[int],
    wp: int,
    wa: int,
    labels: list[str],
    expected_hidden: int,
    expected_hashes: dict[int, tuple[str, str]] | None = None,
) -> tuple[dict | None, str]:
    """(shard blob, "ok") when an existing shard matches the CURRENT regime.

    Never skip on file-existence alone: a prior ``--smoke`` (20 contexts, 2
    stub rows) or a different-window run leaves a shard at the SAME path whose
    silent reuse corrupts the production store. Checks: loadable; corpus;
    window args (wp, wa); row labels (layer count + names); the EXACT expected
    context-id set for the shard's index range; per-context h dtype fp16,
    rank 3, row count == len(labels), hidden dim. Returns ``(None, reason)``
    on any mismatch (caller recaptures; fail-loud on a second mismatch).

    ``expected_hashes`` (ci → (prompt_sha256, response_sha256), computed from
    the CURRENT items via ``content_hashes``) adds CONTENT identity on top of
    the ci-set/shape keys — the ``eval_repaired`` hardening (concern
    ``eval-repaired-response-identity-unchecked``): a shard captured under
    DIFFERENT completions with the same ci set and token counts is otherwise
    silently reused. A record MISSING the hash fields (a pre-hash shard) is
    INVALID — no silent grandfathering. ``None`` (the lmsys / eval_subset
    callers, whose pinned production shards predate the fields) skips the
    content check unchanged.
    """
    try:
        blob = torch.load(path, weights_only=False)
    except Exception as e:
        return None, f"unloadable ({type(e).__name__}: {e})"
    if blob.get("corpus") != corpus:
        return None, f"corpus {blob.get('corpus')!r} != {corpus!r}"
    win = blob.get("window") or {}
    if (win.get("wp"), win.get("wa")) != (wp, wa):
        return None, f"window {win} != (wp={wp}, wa={wa})"
    if blob.get("blocks") != labels:
        return None, f"row labels mismatch ({len(blob.get('blocks') or [])} vs {len(labels)} rows)"
    contexts = blob.get("contexts") or {}
    cis = {int(ci) for ci in contexts}
    if cis != expected_cis:
        return None, (
            f"context-id set mismatch (have {len(cis)}, want {len(expected_cis)}; "
            f"missing {sorted(expected_cis - cis)[:3]}, extra {sorted(cis - expected_cis)[:3]})"
        )
    for ci, rec in contexts.items():
        hh = rec.get("h")
        if (
            hh is None
            or hh.dtype != torch.float16
            or hh.dim() != 3
            or hh.shape[1] != len(labels)
            or hh.shape[2] != expected_hidden
        ):
            got = None if hh is None else (hh.dtype, tuple(hh.shape))
            return (
                None,
                f"ci={ci} h invalid: {got} (want fp16 (n_pos, {len(labels)}, {expected_hidden}))",
            )
        if expected_hashes is not None:
            got_h = (rec.get("prompt_sha256"), rec.get("response_sha256"))
            if got_h[0] is None or got_h[1] is None:
                return None, (
                    f"ci={ci} missing content-hash fields (pre-hash shard — "
                    "no silent grandfathering)"
                )
            want_h = expected_hashes[int(ci)]
            if got_h != want_h:
                which = "prompt" if got_h[0] != want_h[0] else "response"
                return None, (
                    f"ci={ci} {which}_sha256 mismatch vs the CURRENT completions items "
                    "(shard captured under different content)"
                )
    return blob, "ok"


# ── main ──────────────────────────────────────────────────────────────────────


def main() -> int:
    ap = argparse.ArgumentParser(description="Issue #922 per-position window capture.")
    ap.add_argument("--corpus", choices=("lmsys", "eval_subset", "eval_repaired"), required=True)
    ap.add_argument(
        "--completions",
        type=Path,
        default=None,
        help="eval_repaired: the repair gen phase's fresh-completions JSON (required)",
    )
    ap.add_argument("--out", type=Path, default=Path("/workspace/issue922_store"))
    ap.add_argument("--batch", type=int, default=16)
    ap.add_argument("--wp", type=int, default=C.W_P)
    ap.add_argument("--wa", type=int, default=C.W_A)
    ap.add_argument("--model", default=C.DEFAULT_MODEL)
    ap.add_argument("--tokenizer", default=None, help="defaults to --model")
    ap.add_argument("--n-contexts", type=int, default=None, help="lmsys truncation (smoke)")
    ap.add_argument("--n-per-cell", type=int, default=C.EVAL_N_PER_CELL)
    ap.add_argument("--seed", type=int, default=C.EVAL_SUBSET_SEED)
    ap.add_argument("--smoke", action="store_true", help="20 lmsys ctx / 1 eval cell")
    ap.add_argument("--parity", choices=("assert", "report", "skip"), default="assert")
    ap.add_argument("--parity-tol-cos", type=float, default=0.99)
    ap.add_argument("--expected-layers", type=int, default=C.EXPECTED_LAYERS)
    ap.add_argument("--expected-hidden", type=int, default=C.EXPECTED_HIDDEN)
    args = ap.parse_args()

    from transformers import AutoModelForCausalLM, AutoTokenizer

    tokenizer = AutoTokenizer.from_pretrained(args.tokenizer or args.model)
    assert_template_tail(tokenizer)
    use_cuda = torch.cuda.is_available()
    if use_cuda:
        model = AutoModelForCausalLM.from_pretrained(
            args.model, torch_dtype=torch.bfloat16, device_map={"": torch.device("cuda:0")}
        )
        free_b, _ = torch.cuda.mem_get_info()
        if free_b < 60 * (1 << 30) and args.batch > 1:
            args.batch = max(1, args.batch // 2)
            logger.warning("[hbm] <60 GB free — batch halved to %d", args.batch)
    else:
        model = AutoModelForCausalLM.from_pretrained(args.model, torch_dtype=torch.float32)
    model.eval()
    n_layers = len(model.model.layers)
    assert n_layers == args.expected_layers, (n_layers, args.expected_layers)
    assert model.config.hidden_size == args.expected_hidden, model.config.hidden_size

    gate = equivalence_gate(model, tokenizer, args.wp, args.wa)

    if args.corpus == "lmsys":
        n_ctx = 20 if args.smoke else (args.n_contexts or C.N_LMSYS)
        items = C.load_lmsys_items(n_contexts=n_ctx)
    elif args.corpus == "eval_repaired":
        assert args.completions is not None, "--corpus eval_repaired requires --completions"
        items = load_repair_items(args.completions)
    else:
        items = C.build_eval_subset_items(
            n_per_cell=args.n_per_cell,
            seed=args.seed,
            smoke_cells=1 if args.smoke else None,
        )
    logger.info("[inputs] corpus=%s n_items=%d", args.corpus, len(items))

    # Content-identity keys for the shard-resume validation (eval_repaired
    # only — lmsys/eval_subset production shards predate the hash fields and
    # keep the ci-set/shape validation unchanged).
    expected_hashes = None
    if args.corpus == "eval_repaired":
        expected_hashes = {int(it["ci"]): content_hashes(tokenizer, it) for it in items}

    out_dir = args.out / args.corpus
    out_dir.mkdir(parents=True, exist_ok=True)
    t0 = time.time()
    n_shards = (len(items) + C.SHARD_CTX - 1) // C.SHARD_CTX
    all_rows_by_ci: dict[int, dict] = {}
    empty_answers = 0
    ans_lens: list[int] = []
    _mods, labels = _resolve_rows(model)
    for k in range(n_shards):
        path = C.shard_path(args.out, args.corpus, k)
        shard_items = items[k * C.SHARD_CTX : (k + 1) * C.SHARD_CTX]
        if path.exists():
            blob, why = validate_shard(
                path,
                corpus=args.corpus,
                expected_cis={int(it["ci"]) for it in shard_items},
                wp=args.wp,
                wa=args.wa,
                labels=labels,
                expected_hidden=args.expected_hidden,
                expected_hashes=expected_hashes,
            )
            if blob is not None:
                logger.info("[shard %d/%d] exists + regime-valid — skip (resume)", k + 1, n_shards)
                if args.corpus == "eval_subset" and args.parity != "skip":
                    all_rows_by_ci.update({int(ci): r for ci, r in blob["contexts"].items()})
                continue
            logger.warning(
                "[shard %d/%d] exists but FAILS validation (%s) — recapturing", k + 1, n_shards, why
            )
        tok_items = [tokenize_item(tokenizer, it, args.wp, args.wa) for it in shard_items]
        empty_answers += sum(1 for it in tok_items if it["ans_len"] == 0)
        ans_lens.extend(it["ans_len"] for it in tok_items)
        rows = capture_windows_batched(model, tokenizer, tok_items, args.batch)
        contexts = {int(it["ci"]): r for it, r in zip(shard_items, rows, strict=True)}
        all_rows_by_ci.update(contexts)
        torch.save(
            {
                "corpus": args.corpus,
                "blocks": labels,
                "contexts": contexts,
                "window": {"wp": args.wp, "wa": args.wa},
                "metadata": C.reproducibility_metadata(
                    {"script": "issue922_capture_positions", "corpus": args.corpus, "shard": k}
                ),
            },
            path,
        )
        # fail-loud on a second mismatch (plan §4.2): the shard we JUST wrote
        # must validate under the current regime — anything else is a bug.
        _blob2, why2 = validate_shard(
            path,
            corpus=args.corpus,
            expected_cis={int(it["ci"]) for it in shard_items},
            wp=args.wp,
            wa=args.wa,
            labels=labels,
            expected_hidden=args.expected_hidden,
            expected_hashes=expected_hashes,
        )
        if _blob2 is None:
            raise RuntimeError(f"freshly-written shard {path} fails validation: {why2}")
        del _blob2
        el = time.time() - t0
        done = min((k + 1) * C.SHARD_CTX, len(items))
        logger.info(
            "[shard %d/%d] saved %s (%d ctx; %.1fs elapsed; projected total %.1fs)",
            k + 1,
            n_shards,
            path.name,
            len(contexts),
            el,
            el / max(done, 1) * len(items),
        )

    parity = None
    if args.corpus == "eval_subset" and args.parity != "skip":
        parity = parity_probe(
            all_rows_by_ci,
            [it for it in items if it["ci"] in all_rows_by_ci],
            args.parity,
            args.parity_tol_cos,
        )

    # Store-size projection vs the §9 arithmetic (smoke acceptance: within 1.3×).
    realized_bytes = sum(p.stat().st_size for p in out_dir.glob("shard_*.pt"))
    n_rows = len(labels)
    per_ctx_bound = (args.wp + args.wa) * n_rows * args.expected_hidden * 2
    summary = {
        "corpus": args.corpus,
        "n_items": len(items),
        "n_rows": n_rows,
        "equivalence_gate": gate,
        "parity_probe": parity,
        "empty_answers": empty_answers,
        "ans_len_median": float(np.median(ans_lens)) if ans_lens else None,
        "ans_len_ge_wa_frac": float(np.mean([a >= args.wa for a in ans_lens]))
        if ans_lens
        else None,
        "realized_store_bytes": realized_bytes,
        "per_ctx_upper_bound_bytes": per_ctx_bound,
        "projected_full_gb": per_ctx_bound
        * (C.N_LMSYS if args.corpus == "lmsys" else len(items))
        / 1e9,
        "wall_seconds": time.time() - t0,
        "smoke": args.smoke,
    }
    C.write_json_atomic(
        out_dir / "capture_summary.json",
        {**summary, "metadata": C.reproducibility_metadata({"script": "issue922_capture"})},
    )
    logger.info("DONE: %s", json.dumps({k: v for k, v in summary.items() if k != "parity_probe"}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
