# ruff: noqa: RUF001  # Greek rho in figure text intentional
"""Regenerate the missing #507 hero figure: paired per-source |Spearman rho| at 7B vs 72B.

Reads eval_results/issue_507/cross_arm_comparison.json (committed aggregate of the
#470 7B regression and the #507 72B regression) and writes
figures/issue_507/hero_per_source_rho_7b_vs_72b.{png,pdf,meta.json}.

The clean-result body of task #507 cites this figure by name; it was never
generated by the on-pod phase6_figures.py run, so the body's pinned raw URL
404'd (caught at promotion review, 2026-06-09).
"""

from __future__ import annotations

import json
from pathlib import Path

from explore_persona_space.orchestrate.env import load_dotenv

# #847: thread caps must land BEFORE the numpy/torch imports below — on the
# shared VM, load_dotenv() setdefaults OMP/MKL/OPENBLAS/NUMEXPR_NUM_THREADS,
# and the BLAS/torch pools freeze at import time.
load_dotenv()

import matplotlib.pyplot as plt  # noqa: E402

from explore_persona_space.analysis.paper_plots import (  # noqa: E402
    add_direction_arrow,
    paper_palette_blog,
    savefig_paper,
    set_paper_style,
    set_title_subtitle,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
COMPARISON_JSON = REPO_ROOT / "eval_results" / "issue_507" / "cross_arm_comparison.json"

# Reader-facing labels for source-persona keys (figure-side mirror of
# clean-result-critic Lens 3 — no raw config slugs on rendered axes).
SOURCE_LABELS = {
    "assistant": "assistant",
    "comedian": "comedian",
    "kindergarten_teacher": "kindergarten teacher",
    "qwen_default": "Qwen default",
    "software_engineer": "software engineer",
    "villain": "villain",
}
SOURCE_ORDER = list(SOURCE_LABELS)

PANELS = [
    ("cosine_response_headline", "Residual cosine", "layer 20 at 7B vs layer 57 at 72B"),
    ("M_js", "JS divergence (M_js)", "sequence-level response similarity"),
]

RHO_THRESHOLD = 0.20  # pre-specified within-source threshold from the #507 plan


def main() -> int:
    data = json.loads(COMPARISON_JSON.read_text())["per_predictor"]

    set_paper_style("blog")
    blue, orange = paper_palette_blog(2)  # blog palette: [blue, orange, ...]
    c_7b, c_72b = orange, blue  # body caption fixes orange = 7B, blue = 72B

    fig, axes = plt.subplots(1, 2, figsize=(9.5, 4.2), sharey=True)
    xs = range(len(SOURCE_ORDER))

    for ax, (key, title, subtitle) in zip(axes, PANELS, strict=False):
        rho_7b = [abs(data[key]["rho_7b_per_source"][s]) for s in SOURCE_ORDER]
        rho_72b = [abs(data[key]["rho_72b_per_source"][s]) for s in SOURCE_ORDER]

        for x, lo, hi in zip(xs, rho_7b, rho_72b, strict=False):
            ax.plot([x - 0.12, x + 0.12], [lo, hi], color="lightgrey", lw=1.2, zorder=1)
        ax.scatter(
            [x - 0.12 for x in xs], rho_7b, color=c_7b, s=55, zorder=3, label="7B (prior run)"
        )
        ax.scatter(
            [x + 0.12 for x in xs], rho_72b, color=c_72b, s=55, zorder=3, label="72B (this run)"
        )

        ax.axhline(RHO_THRESHOLD, ls=":", lw=1.2, color="#5A5A5A", zorder=2)
        ax.set_xticks(list(xs))
        ax.set_xticklabels([SOURCE_LABELS[s] for s in SOURCE_ORDER], rotation=25, ha="right")
        ax.set_ylim(0, 0.5)
        set_title_subtitle(ax, title, subtitle)

    add_direction_arrow(
        axes[0],
        axis="y",
        direction="up",
        label="|Spearman ρ| (↑ stronger prediction)",
    )
    axes[1].legend(loc="upper right")

    paths = savefig_paper(fig, "issue_507/hero_per_source_rho_7b_vs_72b", dir=REPO_ROOT / "figures")
    plt.close(fig)
    for fmt, path in paths.items():
        print(f"{fmt}: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
