"""Unified artifact factory — shared Behavior + Context specs (task #852, Phase 0b).

This package owns the spec objects the artifact-factory phases share: one
:class:`Behavior` per behavior (data-gen + training + eval + direction
extraction read the SAME spec) and one :class:`Context` typology with ONE
message resolver. Downstream Phase-0 tasks (0c negatives, 0d datagen, 0e
recipe, 0f directions, 0g organisms) add modules INTO this package; this
module owns the package skeleton and the public field-name contract they read.
"""

from explore_persona_space.artifacts.behavior import (
    ALLOWED_COMPANION_DVS,
    ALLOWED_PRIMARY_DVS,
    BEHAVIORS,
    DEFAULT_JUDGE_MODEL,
    EXTRACTION_PAIR_COUNT,
    METHODS,
    Behavior,
    DVSpec,
    ElicitationSpec,
    ExtractionSpec,
    PromptPair,
)
from explore_persona_space.artifacts.context import (
    CONTEXT_KINDS,
    CONTEXTS,
    FAMILY_KIND_MAP,
    INSTALLABLE_KINDS,
    Context,
    context_for_persona,
    validate_context,
)
from explore_persona_space.artifacts.negatives import (
    DEFAULT_ASSISTANT_NEGATIVE,
    DEFAULT_PANEL_NAME,
    ISSUE664_PANEL_NAME,
    NEGATIVE_PANELS,
    NegativeContext,
    assert_panel_disjoint_from_sources,
    default_panel,
    get_panel,
    negative_allocation,
    per_negative_quota,
    register_panel,
)
from explore_persona_space.artifacts.recipe import (
    ARMS,
    CHECKPOINT_EVERY_STEPS,
    CONTENT_EPOCHS_CEILING,
    DEFAULT_GENERIC_FRAC,
    DEFAULT_NEG_RATIO,
    FACT_OVERRIDES,
    JUDGED_RATE_BAND,
    LOAD_BEARING_KEYS,
    MARKER_NAT_BAND,
    MARKER_OVERRIDES,
    MARKER_TEXT,
    MARKER_TOKEN_ID,
    QWEN_IM_END_ID,
    TRAIN_METHODS,
    UNIFIED_OVERRIDES,
    ZERO3_CONFIG,
    DoseSelection,
    RecipeSpec,
    StoppingSpec,
    TfMarginBandStopCallback,
    build_train_config,
    fullft_launch_command,
    make_tf_margin_probe,
    mix_counts,
    recipe_for,
    select_dose_checkpoint,
)

__all__ = [
    "ALLOWED_COMPANION_DVS",
    "ALLOWED_PRIMARY_DVS",
    "ARMS",
    "BEHAVIORS",
    "CHECKPOINT_EVERY_STEPS",
    "CONTENT_EPOCHS_CEILING",
    "CONTEXTS",
    "CONTEXT_KINDS",
    "DEFAULT_ASSISTANT_NEGATIVE",
    "DEFAULT_GENERIC_FRAC",
    "DEFAULT_JUDGE_MODEL",
    "DEFAULT_NEG_RATIO",
    "DEFAULT_PANEL_NAME",
    "EXTRACTION_PAIR_COUNT",
    "FACT_OVERRIDES",
    "FAMILY_KIND_MAP",
    "INSTALLABLE_KINDS",
    "ISSUE664_PANEL_NAME",
    "JUDGED_RATE_BAND",
    "LOAD_BEARING_KEYS",
    "MARKER_NAT_BAND",
    "MARKER_OVERRIDES",
    "MARKER_TEXT",
    "MARKER_TOKEN_ID",
    "METHODS",
    "NEGATIVE_PANELS",
    "QWEN_IM_END_ID",
    "TRAIN_METHODS",
    "UNIFIED_OVERRIDES",
    "ZERO3_CONFIG",
    "Behavior",
    "Context",
    "DVSpec",
    "DoseSelection",
    "ElicitationSpec",
    "ExtractionSpec",
    "NegativeContext",
    "PromptPair",
    "RecipeSpec",
    "StoppingSpec",
    "TfMarginBandStopCallback",
    "assert_panel_disjoint_from_sources",
    "build_train_config",
    "context_for_persona",
    "default_panel",
    "fullft_launch_command",
    "get_panel",
    "make_tf_margin_probe",
    "mix_counts",
    "negative_allocation",
    "per_negative_quota",
    "recipe_for",
    "register_panel",
    "select_dose_checkpoint",
    "validate_context",
]
